# Imports

In [1]:
import importlib.metadata
import warnings
from datetime import datetime

import pandas as pd
from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet

# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.89.0

In [2]:
# Project settings (dataset period, data paths): see src/config.py
import sys
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "src" / "config.py").is_file())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.config import DATA_DIR, PERIOD_START, PERIOD_END, select_period
print(f"Dataset period: {PERIOD_START} to {PERIOD_END} (CET, UTC+1)")

Dataset period: 2024-08-22 00:00:00 to 2025-06-05 00:00:00 (CET, UTC+1)

# Merge L1 results to parquet

In [3]:
# Search original files and store filepaths in list
SOURCEDIR = str(DATA_DIR / "FLUXES" / "LGR")
sourcefiles = search_files(searchdirs=SOURCEDIR, pattern='*')
sourcefiles

[WindowsPath('C:/Users/turcof/Desktop/TAN/dataset_ch-tan_ley_2024-25_flux_product/data/FLUXES/LGR/eddypro_CH-TAN_FR-20250819-170305_fluxnet_2025-08-20T224041_adv.csv')]

In [4]:
# Read data from files to dataframe
d = MultiDataFileReader(filepaths=sourcefiles,
                        filetype='EDDYPRO-FLUXNET-CSV-30MIN',
                        output_middle_timestamp=True)
df = d.data_df
df

Reading file eddypro_CH-TAN_FR-20250819-170305_fluxnet_2025-08-20T224041_adv.csv ...

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_MODEL_SA,BADM_INST_HEIGHT_SA,BADM_INST_SA_WIND_FORMAT,BADM_INST_SA_GILL_ALIGN,BADM_SA_OFFSET_NORTH,BADM_INST_MODEL_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_MODEL_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_MODEL_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_MODEL_GA_N2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,CUSTOM_FILTER_NR,CO2_NR,CH4_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CO2_MEAS_MEDIAN,CH4_MEAS_MEDIAN,CO2_MEAS_P25,CH4_MEAS_P25,CO2_MEAS_P75,CH4_MEAS_P75,CO2_MEAS_SIGMA,CH4_MEAS_SIGMA,CO2_MEAS_SKW,CH4_MEAS_SKW,CO2_MEAS_KUR,CH4_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_CH4_MEAS_COV,CO2_MEAS_N2O_MEAS_COV,CH4_MEAS_N2O_MEAS_COV,CO2_NUM_SPIKES,CH4_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CH4_DIAG_NREX,CO2_SPIKE_NREX,CH4_SPIKE_NREX,CO2_ABSLIM_NREX,CH4_ABSLIM_NREX,CO2_VM97_TEST,CH4_VM97_TEST,CO2_LGD,CH4_LGD,CO2_KID,CH4_KID,CO2_ZCD,CH4_ZCD,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_CH4_MEAN,CUSTOM_N2O_MEAN,CUSTOM_T_UNKNOWN_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_FIT_FLAG_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILENAME_HF,FILE_NR,FC_NR,FCH4_NR,FN2O_NR,FC,FH2O,FCH4,FN2O,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FCH4_RANDUNC_HF,FN2O_RANDUNC_HF,FC_VADV,FH2O_VADV,FCH4_VADV,FN2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FCH4_UNCORR,FN2O_UNCORR,FC_STAGE1,FH2O_STAGE1,FCH4_STAGE1,FN2O_STAGE1,FC_STAGE2,FH2O_STAGE2,FCH4_STAGE2,FN2O_STAGE2,FH2O_CELL_CO2,FH2O_CELL_CH4,FH2O_CELL_N2O,FC_SCF,FH2O_SCF,FCH4_SCF,FN2O_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FCH4_CORRDIFF,FN2O_CORRDIFF,FC_NSR,FH2O_NSR,FCH4_NSR,FN2O_NSR,FC_SS,FH2O_SS,FCH4_SS,FN2O_SS,FC_SS_TEST,FH2O_SS_TEST,FCH4_SS_TEST,FN2O_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FCH4_SSITC_TEST,FN2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_N2O_MEAS_COV,H_UNCORR,H_STAGE1,H_STAGE2,H_CELL_CO2,H_CELL_H2O,H_CELL_CH4,H_CELL_N2O,H_BU_BOT,H_BU_TOP,H_BU_SPAR,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_CH4,HPATH_GA_N2O,INST_LI7200_HEAD_DETECT,INST_LI7200_T_OUT,INST_LI7200_T_IN,INST_LI7200_AUX_IN,INST_LI7200_DELTA_P,INST_LI7200_CHOPPER,INST_LI7200_DETECTOR,INST_LI7200_PLL,INST_LI7200_SYNC,INST_LI7500_CHOPPER,INST_LI7500_DETECTOR,INST_LI7500_PLL,INST_LI7500_SYNC,INST_LI7700_NOT_READY,INST_LI7700_NO_SIGNAL,INST_LI7700_RE_UNLOCKED,INST_LI7700_BAD_TEMP,INST_LI7700_LASER_T_UNREG,INST_LI7700_BLOCK_T_UNREG,INST_LI7700_MOTOR_SPINNING,INST_LI7700_PUMP_ON,INST_LI7700_TOP_HEATER_ON,INST_LI7700_BOTTOM_HEATER_ON,INST_LI7700_CALIBRATING,INST_LI7700_MOTOR_FAILURE,INST_LI7700_BAD_AUX_TC1,INST_LI7700_BAD_AUX_TC2,INST_LI7700_BAD_AUX_TC3,INST_LI7700_BOX_CONNECTED,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,INST_LI7700_RSSI,KRYPTON_HYDRO_KH2O_GA_H2O,KRYPTON_HYDRO_KO2_GA_H2O,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,LOGGER_SWVER_MAJOR,LOGGER_SWVER_MINOR,LOGGER_SWVER_REVISION,LW_IN_1_1_1,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_CH4,MV_AIR_CELL_N2O,MANUFACTURER_SA,MANUFACTURER_GA_CO2,MANUFACTURER_GA_H2O,MANUFACTURER_GA_CH4,MANUFACTURER_GA_N2O,NIGHT,N2O_NR,N2O_MEAS_TYPE,N2O_MOLAR_DENSITY,N2O_MIXING_RATIO,N2O,N2O_TLAG_ACTUAL,N2O_TLAG_USED,N2O_TLAG_NOMINAL,N2O_TLAG_MIN,N2O_TLAG_MAX,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_KUR,N2O_NUM_SPIKES,N2O_DIAG_NREX,N2O_SPIKE_NREX,N2O_ABSLIM_NREX,N2O_VM97_TEST,N2O_LGD,N2O_KID,N2O_ZCD,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,PA_1_1_1,PPFD_IN_1_1_1,RH_EP,ROT_YAW,ROT_PITCH,ROT_ROLL,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_N2O,RH_1_1_1,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SCH4_SINGLE,SN2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SPEC_CORR_LI7700_A,SPEC_CORR_LI7700_B,SPEC_CORR_LI7700_C,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,SW_IN_1_1_1,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,TA_1_1_1,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_CH4,VPATH_GA_N2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_CH4_MEAS_COV,W_N2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-11-07 15:45:00,0.024459,1.18057,1191.96,1009.65,0.0,1.0,-0.104503,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,33907.0,NaN,NaN,NaN,NaN,0.0,0.004084,2056.92,2040.39,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.04999,NaN,2.03928,NaN,2.06459,NaN,0.026416,NaN,1.687580,NaN,6.45396,NaN,NaN,NaN,-0.000007,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800000111.0,NaN,1.45,NaN,4.71668,NaN,17104.0,33.0,0.504881,2.04037,0.334208,47.4481,0.95,3.0,311.646,311.666,94.5797,1.17462,0.024659,0.0,0.0,0.34,36000.0,0.004106,0.001208,0.002920,0.002920,0.002920,1.40623,0.057478,0.0,NaN,36000.0,NaN,33907.0,33907.0,NaN,0.063369,-18.73130,-0.069361,NaN,0.018644,9.77577,0.205045,NaN,5.674690e-14,1.433520e-11,2.348090e-12,22.4901,-3.41295,7.72011,19.2242,29.3181,41.1190,49.2089,61.6038,NaN,0.045063,-11.009500,-0.064029,NaN,0.045063,-11.009500,-0.064029,NaN,0.045063,-11.009500,-0.064029,NaN,NaN,NaN,NaN,1.40623,1.70137,1.08328,NaN,0.057478,0.008068,0.022674,NaN,0.783730,1.911990,0.549682,NaN,2.0,27.0,133.0,NaN,1.0,2.0,6.0,NaN,0.0,0.0,2.0,0.0,360.0,33907.0,33907.0,-0.296263,0.405821,1.0,16.1673,8.14275,8.07698,1.65,1.65,1.65,1.4,3.0,8.04152,7.95401,8.12923,0.133112,-0.185823,3.06162,0.000752,-0.000031,-0.168951,-0.168951,-0.288637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02642,0.0,0.0,0.0,0.0,800000001.0,1.6,5.08671,17100.0,0.039091,3.728430,143.0,6.0,2.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,33907.0,2.834980,0.834096,2.016010,2.016010,2.016010,1.40623,0.057478,0.0,NaN,NaN,NaN,271.667,3372.8100,5811.7200,NaN,0.499588,0.499588,0.499588,NaN,NaN,NaN,NaN,NaN,0.0,33907.0,0.0,0.000669,336.921,334.212,1.4,1.4,1.4,1.0,1.8,0.336843,0.335467,0.338169,0.002384,0.408973,4.36558,0.0,0.0,0.0,0.0,800000011.0,1.35,7.12347,17107.0,7.0,6.0,95.3500,5.28834,95.3500,134.556000,75.2000,46.1374,1.78762,NaN,0.08,0.02,NaN,0.1,0.1,0.1,75.2000,267.16400,33907.0,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.005040,2482680.0,NaN,NaN,NaN,0.0,4.0,65.666700,2.023111e+11,33907.0,33907.0,-0.061388,0.007171,0.600401,-0.001090,14.1285,7.36667,3.23349,14.12,14.09,14.16,0.063338,0.648345,4.81246,-0.060675,-0.061388,-0.061388,44.6260,1.01174,86.0,169.0,0.0,801000111.0,0.0,18.30680,15470.0,0.021502,0.376819,1.0,245.0,1.0,6.0,0.0,1.0,7.36667,1.645400,2.37570,0.228032,2.30049,1.84719,2.83140,0.765680,0.425654,3.02780,0.226705,8.0,12.0,0.0,800000000.0,0.0,7.76702,14.0,15.0,2.0,1.712060,2.566390e-14,0.005951,7.70346,10.24400,2.54050,0.005066,-0.003421,-0.515508,0.449916,0.735135,0.263470,3.28923,39.0,72.0,0.0,800000000.0,80100.0,80100.0,80.0,81.0,0.0,7.59743,131.0,12.5,NaN,28.0,28.0,28.0,33907.0,0.074109,3.509980e-15,2.37570,5.24356,247.240,19.3050,-0.005830,-0.159624,0.156614,0.272238,0.066080,4.66270,-0.046808,-0.000142,NaN,0.001102,-0.000271,-1.578860e-06,-0.000054,-0.000120,-0.000217,-0.000328,-0.000442,-0.000537,-0.000600,-0.000638,-0.000628,-0.000544,8.0,0.0,11.0,0.0,800000000.0,0.0,7.55335,14.0,19.0,2.0,0.0,0.0,0.000501,0.000291
2023-11-07 16:15:00,0.024448,1.18107,1192.57,1009.74,0.0,1.0,-1.155120,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,36000.0,NaN,NaN,NaN,NaN,0.0,0.003884,2055.97,2039.08,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.05119,NaN,2.04456,NaN,2.05971,NaN,0.020089,NaN,2.319250,NaN,9.74080,NaN,NaN,NaN,0.000002,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800001111.0,NaN,1.45,NaN,6.11444,NaN,18125.0,33.0,0.503889,2.03904,0.334307,47.4801,0.95,3.0,311.666,311.687,94.5875,1.17499,0.024651,0.0,0.0,0.34,36000.0,0.006952,0.002756,0.005066,0.005066,0.005066,1.37231,0.000905,1.0,NaN,36000.0,NaN,36000.0,36000.0,NaN,0.107283,-4.30116,0.320649,NaN,0.042537,5.25593,0.124789,NaN,5.047570e-14,1.249410e-11,2.048420e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.078177,-2.669360,0.295447,NaN,0.078177,-2.669360,0.295447,NaN,0.078177,-2.669360,0.295447,NaN,NaN,NaN,NaN,1.37231,1.61131,1.08530,NaN,0.000905,0.007448,0.002244,NaN,0.770812,0.582154,0.588735,NaN,52.0,90.0,4.0,NaN,4.0,5.0,1.0,NaN,1.0,1.0,0.0,0.0,360.0,36000.0,36000.0,-5.544480,0.514667,1.0,15.6927,8.30620,8.23778,1.65,1.65,1.65,1.4,3.0,8.20683,8.10983,8.31355,0.151473,0.321722,2.95509,0.001039,0.000025,-5.203780,-5.203780,-5.398500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02704,1.0,0.0,2.0,0.0,800000000.0,1.6,4.80733,18122.0,0.016272,0.980613,4.0,1.0,0.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,36000.0,4.799900,1.903140,3.497670,3.497670,3.497670,1.37231,0.000905,1.0,NaN,NaN,NaN,309.667,96.1322,100.5720,NaN,0.524944,0.524944,0.524944,NaN,NaN,NaN,NaN,NaN,0.0,36000.0,0.0,0.000637,337.077,334.308,1.4,1.4,1.4,1.0,1.8,0.337155,0.335836,0.338301,0.001698,-0.066421,2.56853,0.0,0.0,0.0,0.0,800000011.0,1.35,5.52639,18130.0,7.0,6.0,95.3733,5.04337,95.3733,54.595100,77.0667,49.4614,2.04700,NaN,0.08,0.02,NaN,0.1,0.1,0.1,77.0667,168.35800,36000.0,-0.089664,0.326971,0.000474,NaN,0.007308,-0.059239,0.004324,0.005141,2482830.0,NaN,NaN,NaN,0.0,4.0,27.333300,2.023111e+11,36000.0,36000.0,-0.040387,0.005945,0.565629,-0.025142,14.0625,7.30000,3.51602,14.07,14.03,14.10,0.050827,-0.293210,2.87542,-0.039899,-0.040387,-0.040387,45.2873,1.01225,8.0,16.0,0.0,801000011.0,0.0,9.08786,17153.0,0.035920,1.232820,0.0,44.0,1.0,3.0,1.0,1.0,7.30000,1.310570,2.01768,0.184921,1.99414,1.41907,2.58162,0.788707,0.211800,2.51568,0.183799,5.0,9.0,0.0,800000000.0,0.0,12.23850,31.0,41.0,3.0,1.532390,-4.584680e-14,0.006072,7.85875,10.19730,2.33859,0.005168,-0.021533,-0.460614,0.466410,0.663861,0.120429,3.57962,19.0,31.0,0.0,800000000.0,80101.0,80101.0,80.0,80.0,0.0,8.10957,235.0,12.5,NaN,28.0,28.0,28.0,36000.0,0.072070,3.216510e-15,2.01768,5.17510,243.374,21.2881,0.007512,-0.142191,0.154485,0.261699,-0.258009,5.00192,-0.031525,-0.004364,NaN,0.001911,-0.000066,7.283030e-06,-0.004330,-0.004202,-0.004004,-0.003727,-0.003373,-0.002928,-0.002393,-0.001825,-0.001300,-0.000878,2.0,0.0,4.0,0.0,800000101.0,0.0,8.81569,31.0,7.0,1.0,0.0,0.0,0.017580,0.016804
2023-11-07 16:45:00,0.024430,1.18176,1193.50,1009.93,0.0,1.0,-0.448918,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,36000.0,NaN,NaN,NaN,NaN,0.0,0.003867,2081.52,2063.72,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.06325,NaN,2.04954,NaN,2.09248,NaN,0.052240,NaN,2.183620,NaN,7.94592,NaN,NaN,NaN,0.000004,NaN,1.0,0.0,NaN,0.0,NaN,2.0,NaN,0.0,NaN,800001111.0,NaN,1.45,NaN,6.42937,NaN,18130.0,33.0,0.504000,2.06370,0.334381,47.5030,0.95,3.0,311.687,311.708,94.5768,1.17542,0.024642,0.0,0.0,0.34,36000.0,0.006427,0.002405,0.004766,0.004766,0.004766,1.34830,0.017514,0.0,NaN,36000.0,NaN,36000.0,36000.0,NaN,0.099175,5.72280,0.050173,NaN,0.037119,19.08020,0.106846,NaN,-9.569960e-14,-2.298740e-11,-3.724630e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.073555,3.782120,0.045517,NaN,0.073555,3.782120,0.045517,NaN,0.073555,3.782120,0.045517,NaN,NaN,NaN,NaN,1.34830,1.51312,1.10231,NaN,0.017514,0.016181,0.008255,NaN,1.010460,1.043610,1.675790,NaN,9.0,141.0,0.0,NaN,1.0,6.0,1.0,NaN,0.0,2.0,0.0,0.0,360.0,36000.0,36000.0,-1.992170,0.999846,1.0,16.0983,8.66599,8.59154,1.65,1.65,1.65,1.4,3.0,8.53993,8.43511,8.66410,0.164651,0.327461,2.81337,0.000791,0.000042,-1.753860,-1.753860,-1.945100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.02420,0.0,0.0,0.0,0.0,800000000.0,1.6,4.79605,18127.0,0.049171,1.684960,43.0,3.0,1.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,36000.0,4.437720,1.660950,3.291330,3.291330,3.291330,1.34830,0.017514,0.0,NaN,NaN,NaN,337.333,272.0260,303.8440,NaN,0.533691,0.533691,0.533691,NaN,NaN,NaN,NaN,NaN,1.0,36000.0,0.0,0.000627,337.267,334.382,1.4,1.4,1.4,1.0,1.8,0.337298,0.335819,0.338690,0.001892,0.018583,2.42516,0.0,0.0,0.0,0.0,800000011.0,1.35,5.48256,18135.0,7.0,6.0,95.3967,4.96230,95.3967,11.485700,81.1333,32.9954,2.41931,NaN,0.08,0.02,NaN,0.1,0.1,0.1,81.1333,61.77900,36000.0,-0.179467,0.719942,0.001043,NaN,0.016089,1.120350,0.003377,0.005363,2483150.0,NaN,NaN,NaN,0.0,4.0,6.666670,2.023111e+11,36000.0,36000.0,-0.040854,0.007455,0.576129,-0.008977,13.9995,7.16667,4.11689,14.05,13.99,14.10,0.173610,-2.074720,6.40439,-0.040400,-0.040854,-0.040854,45.3890,1.01125,15.0,30.0,0.0,800000111.0,0.0,15.71570,17749.0,0.039154,1.977710,13.0,225.0,1.0,6.0,1.0,1.0,7.16667,1.299840,1.55119,0.185932,1.42476,0.99706,1.91482,0.780558,1.091680,4.33767,0.184895,1.0,2.0,0.0,800000000.0,0.0,12.02880,69.0,39.0,3.0,0.843979,-6.718370e-14,0.006337,8.19824,10.10470,1.90641,0.005391,-0.029499,-0.355619,0.290065,0.702736,0.088211,6.12003,3.0,4.0,0.0,800000100.0,80100.0,80100.0,80.0,81.0,0.0,12.47370,303.0,12.5,NaN,28.0,28.0,28.0,36000.0,0.065479,-5.944700e-15,1.55119,5.08381,262.811,22.5450,0.005028,-0.117357,0.121096,0.221694,-0.210290,6.81205,-0.031297,-0.001470,NaN,0.001797,0.000093,1.121610e-06,-0.002660,-0.002590,-0.002490,-0.002349,-0.002160,-0.001926,-0.001665,-0.001389,-0.001065,-0.000709,3.0,0.0,7.0,0.0,800000101.0,0.0,11.90360,69.0,21.0,2.0,0.0,0.0,0.006213,0.005562

# Restrict to dataset period

22 Aug 2024 to 4 Jun 2025, see `src/config.py`.

In [5]:
df = select_period(df, timestamp='middle')
df

select_period: kept 13776 of 27619 records (2024-08-22 00:15:00 to 2025-06-04 23:45:00, timestamp=middle)

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_MODEL_SA,BADM_INST_HEIGHT_SA,BADM_INST_SA_WIND_FORMAT,BADM_INST_SA_GILL_ALIGN,BADM_SA_OFFSET_NORTH,BADM_INST_MODEL_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_MODEL_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_MODEL_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_MODEL_GA_N2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,CUSTOM_FILTER_NR,CO2_NR,CH4_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CO2_MEAS_MEDIAN,CH4_MEAS_MEDIAN,CO2_MEAS_P25,CH4_MEAS_P25,CO2_MEAS_P75,CH4_MEAS_P75,CO2_MEAS_SIGMA,CH4_MEAS_SIGMA,CO2_MEAS_SKW,CH4_MEAS_SKW,CO2_MEAS_KUR,CH4_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_CH4_MEAS_COV,CO2_MEAS_N2O_MEAS_COV,CH4_MEAS_N2O_MEAS_COV,CO2_NUM_SPIKES,CH4_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CH4_DIAG_NREX,CO2_SPIKE_NREX,CH4_SPIKE_NREX,CO2_ABSLIM_NREX,CH4_ABSLIM_NREX,CO2_VM97_TEST,CH4_VM97_TEST,CO2_LGD,CH4_LGD,CO2_KID,CH4_KID,CO2_ZCD,CH4_ZCD,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_CH4_MEAN,CUSTOM_N2O_MEAN,CUSTOM_T_UNKNOWN_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_FIT_FLAG_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILENAME_HF,FILE_NR,FC_NR,FCH4_NR,FN2O_NR,FC,FH2O,FCH4,FN2O,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FCH4_RANDUNC_HF,FN2O_RANDUNC_HF,FC_VADV,FH2O_VADV,FCH4_VADV,FN2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FCH4_UNCORR,FN2O_UNCORR,FC_STAGE1,FH2O_STAGE1,FCH4_STAGE1,FN2O_STAGE1,FC_STAGE2,FH2O_STAGE2,FCH4_STAGE2,FN2O_STAGE2,FH2O_CELL_CO2,FH2O_CELL_CH4,FH2O_CELL_N2O,FC_SCF,FH2O_SCF,FCH4_SCF,FN2O_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FCH4_CORRDIFF,FN2O_CORRDIFF,FC_NSR,FH2O_NSR,FCH4_NSR,FN2O_NSR,FC_SS,FH2O_SS,FCH4_SS,FN2O_SS,FC_SS_TEST,FH2O_SS_TEST,FCH4_SS_TEST,FN2O_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FCH4_SSITC_TEST,FN2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_N2O_MEAS_COV,H_UNCORR,H_STAGE1,H_STAGE2,H_CELL_CO2,H_CELL_H2O,H_CELL_CH4,H_CELL_N2O,H_BU_BOT,H_BU_TOP,H_BU_SPAR,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_CH4,HPATH_GA_N2O,INST_LI7200_HEAD_DETECT,INST_LI7200_T_OUT,INST_LI7200_T_IN,INST_LI7200_AUX_IN,INST_LI7200_DELTA_P,INST_LI7200_CHOPPER,INST_LI7200_DETECTOR,INST_LI7200_PLL,INST_LI7200_SYNC,INST_LI7500_CHOPPER,INST_LI7500_DETECTOR,INST_LI7500_PLL,INST_LI7500_SYNC,INST_LI7700_NOT_READY,INST_LI7700_NO_SIGNAL,INST_LI7700_RE_UNLOCKED,INST_LI7700_BAD_TEMP,INST_LI7700_LASER_T_UNREG,INST_LI7700_BLOCK_T_UNREG,INST_LI7700_MOTOR_SPINNING,INST_LI7700_PUMP_ON,INST_LI7700_TOP_HEATER_ON,INST_LI7700_BOTTOM_HEATER_ON,INST_LI7700_CALIBRATING,INST_LI7700_MOTOR_FAILURE,INST_LI7700_BAD_AUX_TC1,INST_LI7700_BAD_AUX_TC2,INST_LI7700_BAD_AUX_TC3,INST_LI7700_BOX_CONNECTED,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,INST_LI7700_RSSI,KRYPTON_HYDRO_KH2O_GA_H2O,KRYPTON_HYDRO_KO2_GA_H2O,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,LOGGER_SWVER_MAJOR,LOGGER_SWVER_MINOR,LOGGER_SWVER_REVISION,LW_IN_1_1_1,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_CH4,MV_AIR_CELL_N2O,MANUFACTURER_SA,MANUFACTURER_GA_CO2,MANUFACTURER_GA_H2O,MANUFACTURER_GA_CH4,MANUFACTURER_GA_N2O,NIGHT,N2O_NR,N2O_MEAS_TYPE,N2O_MOLAR_DENSITY,N2O_MIXING_RATIO,N2O,N2O_TLAG_ACTUAL,N2O_TLAG_USED,N2O_TLAG_NOMINAL,N2O_TLAG_MIN,N2O_TLAG_MAX,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_KUR,N2O_NUM_SPIKES,N2O_DIAG_NREX,N2O_SPIKE_NREX,N2O_ABSLIM_NREX,N2O_VM97_TEST,N2O_LGD,N2O_KID,N2O_ZCD,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,PA_1_1_1,PPFD_IN_1_1_1,RH_EP,ROT_YAW,ROT_PITCH,ROT_ROLL,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_N2O,RH_1_1_1,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SCH4_SINGLE,SN2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SPEC_CORR_LI7700_A,SPEC_CORR_LI7700_B,SPEC_CORR_LI7700_C,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,SW_IN_1_1_1,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,TA_1_1_1,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_CH4,VPATH_GA_N2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_CH4_MEAS_COV,W_N2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-08-22 00:15:00,0.024738,1.16533,1179.50,1012.16,0.0,1.0,5.027140,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,36000.0,NaN,NaN,NaN,NaN,0.0,0.005379,2357.52,2329.47,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.36592,NaN,2.34596,NaN,2.37736,NaN,0.029063,NaN,-1.426830,NaN,4.87225,NaN,NaN,NaN,0.000029,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800000011.0,NaN,1.45,NaN,7.64521,NaN,18261.0,33.0,0.507556,2.32939,0.338817,47.4423,0.95,3.0,235.000,235.021,94.3978,1.15624,0.025051,0.0,0.0,0.34,36000.0,-0.000259,0.000296,-0.000214,-0.000214,-0.000214,1.20694,0.031038,1.0,NaN,36000.0,NaN,36000.0,36000.0,NaN,-0.003991,-5.38187,-0.262678,NaN,0.004565,3.101760,0.461859,NaN,-4.353300e-14,-8.132760e-12,-1.182910e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003306,-4.441950,-0.219816,NaN,-0.003306,-4.441950,-0.219816,NaN,-0.003306,-4.441950,-0.219816,NaN,NaN,NaN,NaN,1.20694,1.21160,1.19499,NaN,0.031038,0.007094,0.154014,NaN,1.236290,1.022570,2.13904,NaN,83.0,65.0,130.0,NaN,5.0,4.0,6.0,NaN,1.0,1.0,2.0,0.0,360.0,36000.0,36000.0,-0.894148,0.535394,1.0,28.7913,12.6266,12.4692,1.65,1.65,1.65,1.4,3.0,11.8890,11.8252,11.9671,0.100825,0.438713,2.78424,-0.000269,-0.000053,-0.62235,-0.62235,-0.610913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.46363,0.0,0.0,0.0,0.0,800000001.0,1.6,5.79447,18255.0,0.256603,1.550550,35.0,3.0,1.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,36000.0,-0.177864,0.203483,-0.147368,-0.147368,-0.147368,1.20694,0.031038,1.0,NaN,NaN,NaN,287.964,0.211674,0.220852,NaN,0.433087,0.433087,0.433087,NaN,NaN,NaN,NaN,NaN,1.0,36000.0,0.0,0.000782,342.901,338.820,1.4,1.4,1.4,1.0,1.8,0.341617,0.339825,0.344971,0.004411,1.217000,4.22425,0.0,0.0,0.0,0.0,800000111.0,1.35,5.90357,18266.0,7.0,6.0,95.5900,6.11013,95.5900,0.0000,89.4400,86.1362,0.187709,NaN,0.08,0.02,NaN,0.1,0.1,0.1,89.4400,0.0,36000.0,-0.607464,-0.076360,-0.000111,NaN,-0.001713,4.077140,0.191593,0.007794,2473410.0,NaN,NaN,NaN,0.0,4.0,0.000000,2.024082e+11,36000.0,36000.0,0.000200,0.000739,0.033197,-0.057937,18.2941,11.2767,9.56948,18.30,18.18,18.38,0.197375,0.570364,4.50305,0.000161,0.000200,0.000200,45.1348,1.23773,3.0,7.0,0.0,800000011.0,0.0,25.41780,23953.0,0.047729,0.781083,128.0,422.0,6.0,7.0,2.0,1.0,11.2767,0.003897,0.057826,0.013084,0.008752,-0.087067,0.207973,0.194019,0.565885,2.58896,0.011761,5.0,9.0,0.0,800000011.0,0.0,14.34030,13183.0,289.0,7.0,0.057694,-5.534510e-14,0.009083,11.9225,13.3301,1.40766,0.007856,0.006228,-0.074405,0.093853,0.164150,-0.503280,4.42583,0.0,0.0,0.0,800000011.0,80000.0,80000.0,80.0,81.0,0.0,11.30220,14008.0,12.5,NaN,28.0,28.0,28.0,36000.0,0.000189,-1.512020e-15,0.057826,0.852936,206.8970,95.8380,0.000100,-0.020454,0.020427,0.042482,-0.016165,4.53250,0.000093,-0.000528,NaN,-0.000082,-0.000111,-5.506530e-06,-0.000329,-0.000325,-0.000312,-0.000286,-0.000245,-0.000190,-0.000134,-0.000114,-0.000141,-0.000164,0.0,0.0,0.0,0.0,801000011.0,0.0,11.05330,13215.0,70.0,4.0,0.0,0.0,7.983960,7.652170
2024-08-22 00:45:00,0.024721,1.16619,1180.31,1012.11,0.0,1.0,-1.064200,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,35976.0,NaN,NaN,NaN,NaN,0.0,0.005584,2447.96,2418.92,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.44274,NaN,2.41129,NaN,2.48162,NaN,0.052564,NaN,0.261365,NaN,2.59807,NaN,NaN,NaN,-0.000125,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800000011.0,NaN,1.45,NaN,12.19690,NaN,18266.0,33.0,0.507978,2.41886,0.339024,47.4354,0.95,3.0,235.021,235.042,94.3960,1.15717,0.025031,0.0,0.0,0.34,36000.0,0.003369,0.000957,0.002922,0.002922,0.002922,1.15302,0.063739,1.0,NaN,36000.0,NaN,35976.0,35976.0,NaN,0.051992,21.14000,0.356024,NaN,0.014764,10.141500,0.779504,NaN,1.242240e-13,2.428350e-11,3.403420e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.045092,18.177100,0.316176,NaN,0.045092,18.177100,0.316176,NaN,0.045092,18.177100,0.316176,NaN,NaN,NaN,NaN,1.15302,1.16300,1.12603,NaN,0.063739,0.020380,0.017867,NaN,0.697558,1.675730,1.12861,NaN,34.0,55.0,77.0,NaN,3.0,4.0,5.0,NaN,1.0,1.0,1.0,0.0,360.0,35976.0,35976.0,-2.466670,1.408250,1.0,28.5628,12.5292,12.3742,1.65,1.65,1.65,1.4,3.0,11.8567,11.7838,11.9403,0.120380,0.073770,2.95287,0.001445,-0.000100,-2.25805,-2.25805,-2.371280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.04023,1.0,0.0,1.0,0.0,800000000.0,1.6,5.65845,18259.0,0.046780,1.734820,38.0,3.0,1.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,35976.0,2.317860,0.658207,2.010240,2.010240,2.010240,1.15302,0.063739,1.0,NaN,NaN,NaN,290.715,12.966000,13.619900,NaN,0.433227,0.433227,0.433227,NaN,NaN,NaN,NaN,NaN,1.0,35976.0,0.0,0.000783,343.090,339.021,1.4,1.4,1.4,1.0,1.8,0.342644,0.339738,0.345821,0.004130,0.736501,3.66200,0.0,0.0,0.0,0.0,800000111.0,1.35,5.80783,18276.0,7.0,6.0,95.5790,6.10849,95.5790,0.0000,90.1333,325.6390,-0.647087,NaN,0.08,0.02,NaN,0.1,0.1,0.1,90.1333,0.0,35976.0,-0.310596,-0.190357,-0.000277,NaN,-0.004270,4.020860,0.009007,0.007735,2473960.0,NaN,NaN,NaN,0.0,4.0,0.000000,2.024082e+11,35976.0,35976.0,-0.006103,0.002613,0.168278,-0.028889,18.0501,11.0433,9.45399,18.10,17.89,18.23,0.269874,-0.767554,3.86893,-0.005946,-0.006103,-0.006103,45.1514,1.02645,2.0,3.0,0.0,800000001.0,0.0,25.93850,17185.0,0.004837,0.660857,44.0,327.0,3.0,7.0,1.0,1.0,11.0433,0.112735,0.136575,0.072340,0.308109,-0.351551,0.485051,0.451541,-0.470765,1.92400,0.071402,1.0,2.0,0.0,800000011.0,0.0,6.37583,4874.0,83.0,5.0,-0.077080,1.168990e-14,0.009020,11.8303,13.1253,1.29503,0.007795,-0.045800,-0.272969,0.212019,0.357697,0.427838,2.27362,0.0,0.0,0.0,800000111.0,80111.0,80111.0,80.0,81.0,0.0,6.54785,6289.0,12.5,NaN,28.0,28.0,28.0,35976.0,-0.001542,4.349150e-15,0.136575,1.274790,335.9810,81.7847,0.003576,-0.043812,0.044498,0.068698,-0.147876,3.55408,-0.004007,-0.001913,NaN,0.001115,0.000455,7.914060e-06,-0.001549,-0.001530,-0.001487,-0.001417,-0.001305,-0.001150,-0.000960,-0.000753,-0.000531,-0.000315,0.0,0.0,0.0,0.0,800000011.0,0.0,8.77230,4874.0,44.0,3.0,0.0,0.0,0.130341,0.124083
2024-08-22 01:15:00,0.024713,1.16655,1180.66,1012.10,0.0,1.0,-0.916917,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,NaN,2.03,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,NaN,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,NaN,36000.0,NaN,NaN,NaN,NaN,0.0,0.005392,2363.68,2335.95,NaN,NaN,NaN,NaN,NaN,1.5,1.5,1.5,1.2,1.8,NaN,2.35404,NaN,2.31723,NaN,2.42419,NaN,0.051332,NaN,0.203086,NaN,1.58076,NaN,NaN,NaN,0.000077,NaN,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,800000011.0,NaN,1.45,NaN,6.75808,NaN,18262.0,33.0,0.507556,2.33600,0.338731,47.4394,0.95,3.0,235.042,235.062,94.3750,1.15754,0.025023,0.0,0.0,0.34,36000.0,0.003349,0.000989,0.002838,0.002838,0.002838,1.17988,0.019744,1.0,NaN,36000.0,NaN,36000.0,36000.0,NaN,0.051675,-26.38320,-0.011653,NaN,0.015263,11.533600,0.107261,NaN,1.293530e-13,2.444880e-11,3.545280e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.043796,-22.026500,-0.010329,NaN,0.043796,-22.026500,-0.010329,NaN,0.043796,-22.026500,-0.010329,NaN,NaN,NaN,NaN,1.17988,1.19779,1.12821,NaN,0.019744,0.002304,0.008599,NaN,1.271920,1.110390,0.96930,NaN,14.0,70.0,5655.0,NaN,1.0,4.0,9.0,NaN,1.0,1.0,2.0,0.0,360.0,36000.0,36000.0,-2.112620,1.746000,1.0,28.5286,12.5136,12.3590,1.65,1.65,1.65,1.4,3.0,11.7233,11.6500,11.8038,0.110948,0.312269,2.79051,-0.001145,-0.000131,-1.93139,-1.93139,-2.042370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.03439,4.0,0.0,7.0,0.0,800000001.0,1.6,5.73281,18252.0,0.093602,0.894161,16.0,2.0,1.0,11.0,NaN,4.445,4.445,4.445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.0,9999.0,NaN,NaN,NaN,36000.0,2.304040,0.680537,1.952770,1.952770,1.952770,1.17988,0.019744,1.0,NaN,NaN,NaN,290.553,17.116100,18.170100,NaN,0.433214,0.433214,0.433214,NaN,NaN,NaN,NaN,NaN,1.0,36000.0,0.0,0.000782,342.752,338.732,1.4,1.4,1.4,1.0,1.8,0.342189,0.340088,0.344678,0.003767,1.217380,5.92224,0.0,0.0,0.0,0.0,800000111.0,1.35,6.41582,18265.0,7.0,6.0,95.5563,6.10839,95.5563,0.0000,90.9233,52.5350,0.738498,NaN,0.08,0.02,NaN,0.1,0.1,0.1,90.9233,0.0,36000.0,-0.204166,-0.030438,-0.000044,NaN,-0.000683,-3.730510,-0.012993,0.007725,2474330.0,NaN,NaN,NaN,0.0,4.0,0.000000,2.024082e+11,36000.0,36000.0,0.006626,0.002558,0.119491,-0.023742,17.9694,10.8900,9.43221,17.96,17.80,18.10,0.289831,0.547945,4.44402,0.006495,0.006626,0.006626,45.1372,1.02016,3.0,7.0,0.0,800000011.0,0.0,54.66370,16599.0,0.029842,0.914796,22.0,421.0,2.0,7.0,1.0,1.0,10.8900,0.156042,0.256552,0.075366,0.135091,-0.003119,0.504048,0.399707,0.720652,2.73252,0.074618,1.0,2.0,0.0,800000011.0,0.0,7.22268,4637.0,56.0,4.0,0.203615,-5.091270e-14,0.009012,11.8129,12.9922,1.17926,0.007785,0.013951,-0.218836,0.216103,0.270052,-0.017194,2.30402,3.0,5.0,0.0,800000011.0,80100.0,80100.0,80.0,81.0,0.0,7.67300,5870.0,12.5,NaN,28.0,28.0,28.0,36000.0,0.003307,4.534160e-15,0.256552,1.421090,249.7910,74.5736,0.001305,-0.050907,0.050263,0.079303,-0.151094,4.06894,0.005093,-0.001636,NaN,0.001082,-0.000551,-2.584480e-07,-0.001576,-0.001545,-0.001472,-0.001341,-0.001139,-0.000873,-0.000577,-0.000298,-0.000065,0.000078,0.0,0.0,0.0,0.0,800000011.0,0.0,8.56235,4637.0,38.0,3.0,0.0,0.0,0.098737,0.093010

# Remove vars with zero records

In [6]:
stats = df.describe().T

In [7]:
# Find available variables that have more than 0 records, remove all others from data
available_vars = stats.loc[stats['count'] > 0].index
not_available_vars = stats.loc[stats['count'] == 0].index
print("No records for the following vars:")
print(stats.loc[not_available_vars])

No records for the following vars:
                                       count  mean  std  min  25%  50%  75%  max
BADM_INST_MODEL_SA                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_WIND_FORMAT                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_SA_GILL_ALIGN                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CO2                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_EASTWARD_SEP_GA_CO2        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INSTPAIR_HEIGHT_SEP_GA_CO2          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_H2O                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_CH4                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
BADM_INST_MODEL_GA_N2O                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_NR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_TYPE                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MOLAR_DENSITY                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MIXING_RATIO                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2                                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_ACTUAL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_USED                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_NOMINAL                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_MIN                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_TLAG_MAX                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_MEDIAN                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_P25                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_P75                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_SIGMA                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_SKW                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_KUR                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_H2O_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_CH4_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_MEAS_N2O_MEAS_COV                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_NUM_SPIKES                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_DIAG_NREX                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_SPIKE_NREX                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_ABSLIM_NREX                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_VM97_TEST                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_LGD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_KID                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
CO2_ZCD                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FILENAME_HF                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_NR                                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC                                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_RANDUNC_HF                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_VADV                                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_UNCORR                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_STAGE1                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_STAGE2                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CO2                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_CH4                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FH2O_CELL_N2O                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SCF                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_CORRDIFF                              0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_NSR                                   0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SS                                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SS_TEST                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
FC_SSITC_TEST                            0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CO2                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_H2O                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_CH4                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_CELL_N2O                               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_BOT                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_TOP                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
H_BU_SPAR                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
HPATH_GA_CO2                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_HEAD_DETECT                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_OUT                        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_T_IN                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_AUX_IN                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DELTA_P                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_CHOPPER                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_DETECTOR                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_PLL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7200_SYNC                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_CHOPPER                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_DETECTOR                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_PLL                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7500_SYNC                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NOT_READY                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_NO_SIGNAL                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RE_UNLOCKED                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_TEMP                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_LASER_T_UNREG                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BLOCK_T_UNREG                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_SPINNING               0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_PUMP_ON                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_TOP_HEATER_ON                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOTTOM_HEATER_ON             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_CALIBRATING                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_MOTOR_FAILURE                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC1                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC2                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BAD_AUX_TC3                  0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_BOX_CONNECTED                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
INST_LI7700_RSSI                         0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KH2O_GA_H2O                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
KRYPTON_HYDRO_KO2_GA_H2O                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MAJOR                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_MINOR                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
LOGGER_SWVER_REVISION                    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MV_AIR_CELL_CO2                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_SA                          0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CO2                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_H2O                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_CH4                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
MANUFACTURER_GA_N2O                      0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
ROT_ROLL                                 0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
RESPONSE_TIME_GA_CO2                     0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SC_SINGLE                                0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_A                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_B                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
SPEC_CORR_LI7700_C                       0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
VPATH_GA_CO2                             0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
W_CO2_MEAS_COV                           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [8]:
print("Removing variables with 0 records ...")
df_available = df[available_vars].copy()

print(f"Variables removed:")
df_not_available = df[not_available_vars].copy()
_list = df_not_available.columns.tolist()
for c in _list:
    print(c, end=" ")

Removing variables with 0 records ...
Variables removed:
BADM_INST_MODEL_SA BADM_INST_SA_WIND_FORMAT BADM_INST_SA_GILL_ALIGN BADM_INST_MODEL_GA_CO2 BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2 BADM_INSTPAIR_EASTWARD_SEP_GA_CO2 BADM_INSTPAIR_HEIGHT_SEP_GA_CO2 BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2 BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2 BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2 BADM_INST_MODEL_GA_H2O BADM_INST_MODEL_GA_CH4 BADM_INST_MODEL_GA_N2O CO2_NR CO2_MEAS_TYPE CO2_MOLAR_DENSITY CO2_MIXING_RATIO CO2 CO2_TLAG_ACTUAL CO2_TLAG_USED CO2_TLAG_NOMINAL CO2_TLAG_MIN CO2_TLAG_MAX CO2_MEAS_MEDIAN CO2_MEAS_P25 CO2_MEAS_P75 CO2_MEAS_SIGMA CO2_MEAS_SKW CO2_MEAS_KUR CO2_MEAS_H2O_MEAS_COV CO2_MEAS_CH4_MEAS_COV CO2_MEAS_N2O_MEAS_COV CO2_NUM_SPIKES CO2_DIAG_NREX CO2_SPIKE_NREX CO2_ABSLIM_NREX CO2_VM97_TEST CO2_LGD CO2_KID CO2_ZCD FILENAME_HF FC_NR FC FC_RANDUNC_HF FC_VADV FC_UNCORR FC_STAGE1 FC_STAGE2 FH2O_CELL_CO2 FH2O_CELL_CH4 FH2O_CELL_N2O FC_SCF FC_CORRDIFF FC_NSR FC_SS FC_SS_TEST FC_SSITC_TEST H_CELL_CO2 H_CELL_H2O H_CELL_CH4 H_CELL_N2O H_BU_BOT H_BU_TOP H_BU_SPAR HPATH_GA_CO2 INST_LI7200_HEAD_DETECT INST_LI7200_T_OUT INST_LI7200_T_IN INST_LI7200_AUX_IN INST_LI7200_DELTA_P INST_LI7200_CHOPPER INST_LI7200_DETECTOR INST_LI7200_PLL INST_LI7200_SYNC INST_LI7500_CHOPPER INST_LI7500_DETECTOR INST_LI7500_PLL INST_LI7500_SYNC INST_LI7700_NOT_READY INST_LI7700_NO_SIGNAL INST_LI7700_RE_UNLOCKED INST_LI7700_BAD_TEMP INST_LI7700_LASER_T_UNREG INST_LI7700_BLOCK_T_UNREG INST_LI7700_MOTOR_SPINNING INST_LI7700_PUMP_ON INST_LI7700_TOP_HEATER_ON INST_LI7700_BOTTOM_HEATER_ON INST_LI7700_CALIBRATING INST_LI7700_MOTOR_FAILURE INST_LI7700_BAD_AUX_TC1 INST_LI7700_BAD_AUX_TC2 INST_LI7700_BAD_AUX_TC3 INST_LI7700_BOX_CONNECTED INST_LI7700_RSSI KRYPTON_HYDRO_KH2O_GA_H2O KRYPTON_HYDRO_KO2_GA_H2O LOGGER_SWVER_MAJOR LOGGER_SWVER_MINOR LOGGER_SWVER_REVISION MV_AIR_CELL_CO2 MANUFACTURER_SA MANUFACTURER_GA_CO2 MANUFACTURER_GA_H2O MANUFACTURER_GA_CH4 MANUFACTURER_GA_N2O ROT_ROLL RESPONSE_TIME_GA_CO2 SC_SINGLE SPEC_CORR_LI7700_A SPEC_CORR_LI7700_B SPEC_CORR_LI7700_C VPATH_GA_CO2 W_CO2_MEAS_COV

# Remove meteo variables from EC L1 output

In [9]:
removecols = [v for v in df_available if str(v).endswith("_1_1_1")]
print("The following variables will be removed from EC results:")
print(removecols)

The following variables will be removed from EC results:
['LW_IN_1_1_1', 'PA_1_1_1', 'PPFD_IN_1_1_1', 'RH_1_1_1', 'SW_IN_1_1_1', 'TA_1_1_1']

In [10]:
# Remove meteo data from flux results because this meteo has gaps after flux processing
keepcols = []
[keepcols.append(c) for c in df_available.columns if "_1_1_1" not in c]
df_reduced = df_available[keepcols].copy()
df_reduced

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_HEIGHT_SA,BADM_SA_OFFSET_NORTH,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,CUSTOM_FILTER_NR,CH4_NR,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CH4_MEAS_MEDIAN,CH4_MEAS_P25,CH4_MEAS_P75,CH4_MEAS_SIGMA,CH4_MEAS_SKW,CH4_MEAS_KUR,CH4_MEAS_N2O_MEAS_COV,CH4_NUM_SPIKES,CUSTOM_FILTER_NREX,CH4_DIAG_NREX,CH4_SPIKE_NREX,CH4_ABSLIM_NREX,CH4_VM97_TEST,CH4_LGD,CH4_KID,CH4_ZCD,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_CH4_MEAN,CUSTOM_N2O_MEAN,CUSTOM_T_UNKNOWN_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_FIT_FLAG_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILE_NR,FCH4_NR,FN2O_NR,FH2O,FCH4,FN2O,FH2O_RANDUNC_HF,FCH4_RANDUNC_HF,FN2O_RANDUNC_HF,FH2O_VADV,FCH4_VADV,FN2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FH2O_UNCORR,FCH4_UNCORR,FN2O_UNCORR,FH2O_STAGE1,FCH4_STAGE1,FN2O_STAGE1,FH2O_STAGE2,FCH4_STAGE2,FN2O_STAGE2,FH2O_SCF,FCH4_SCF,FN2O_SCF,FH2O_CORRDIFF,FCH4_CORRDIFF,FN2O_CORRDIFF,FH2O_NSR,FCH4_NSR,FN2O_NSR,FH2O_SS,FCH4_SS,FN2O_SS,FH2O_SS_TEST,FCH4_SS_TEST,FN2O_SS_TEST,FH2O_SSITC_TEST,FCH4_SSITC_TEST,FN2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_N2O_MEAS_COV,H_UNCORR,H_STAGE1,H_STAGE2,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_H2O,HPATH_GA_CH4,HPATH_GA_N2O,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_H2O,MV_AIR_CELL_CH4,MV_AIR_CELL_N2O,NIGHT,N2O_NR,N2O_MEAS_TYPE,N2O_MOLAR_DENSITY,N2O_MIXING_RATIO,N2O,N2O_TLAG_ACTUAL,N2O_TLAG_USED,N2O_TLAG_NOMINAL,N2O_TLAG_MIN,N2O_TLAG_MAX,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_KUR,N2O_NUM_SPIKES,N2O_DIAG_NREX,N2O_SPIKE_NREX,N2O_ABSLIM_NREX,N2O_VM97_TEST,N2O_LGD,N2O_KID,N2O_ZCD,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,RH_EP,ROT_YAW,ROT_PITCH,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_N2O,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SH2O_SINGLE,SCH4_SINGLE,SN2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_H2O,VPATH_GA_CH4,VPATH_GA_N2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_H2O_MEAS_COV,W_CH4_MEAS_COV,W_N2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-08-22 00:15:00,0.024738,1.16533,1179.50,1012.16,0.0,1.0,5.027140,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.005379,2357.52,2329.47,1.5,1.5,1.5,1.2,1.8,2.36592,2.34596,2.37736,0.029063,-1.426830,4.87225,0.000029,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,7.64521,18261.0,33.0,0.507556,2.32939,0.338817,47.4423,0.95,3.0,235.000,235.021,94.3978,1.15624,0.025051,0.0,0.0,0.34,36000.0,-0.000259,0.000296,-0.000214,-0.000214,-0.000214,1.20694,0.031038,1.0,36000.0,36000.0,36000.0,-0.003991,-5.38187,-0.262678,0.004565,3.101760,0.461859,-4.353300e-14,-8.132760e-12,-1.182910e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003306,-4.441950,-0.219816,-0.003306,-4.441950,-0.219816,-0.003306,-4.441950,-0.219816,1.20694,1.21160,1.19499,0.031038,0.007094,0.154014,1.236290,1.022570,2.13904,83.0,65.0,130.0,5.0,4.0,6.0,1.0,1.0,2.0,0.0,360.0,36000.0,36000.0,-0.894148,0.535394,1.0,28.7913,12.6266,12.4692,1.65,1.65,1.65,1.4,3.0,11.8890,11.8252,11.9671,0.100825,0.438713,2.78424,-0.000269,-0.000053,-0.62235,-0.62235,-0.610913,1.46363,0.0,0.0,0.0,0.0,800000001.0,1.6,5.79447,18255.0,0.256603,1.550550,35.0,3.0,1.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,-0.177864,0.203483,-0.147368,-0.147368,-0.147368,1.20694,0.031038,1.0,0.211674,0.220852,0.433087,0.433087,0.433087,1.0,36000.0,0.0,0.000782,342.901,338.820,1.4,1.4,1.4,1.0,1.8,0.341617,0.339825,0.344971,0.004411,1.217000,4.22425,0.0,0.0,0.0,0.0,800000111.0,1.35,5.90357,18266.0,7.0,6.0,95.5900,6.11013,89.4400,86.1362,0.187709,0.08,0.02,0.1,0.1,0.1,0.0,36000.0,-0.607464,-0.076360,-0.000111,-0.001713,4.077140,0.191593,0.007794,2473410.0,0.0,4.0,2.024082e+11,36000.0,36000.0,0.000200,0.000739,0.033197,-0.057937,18.2941,11.2767,9.56948,18.30,18.18,18.38,0.197375,0.570364,4.50305,0.000161,0.000200,0.000200,45.1348,1.23773,3.0,7.0,0.0,800000011.0,0.0,25.41780,23953.0,0.047729,0.781083,128.0,422.0,6.0,7.0,2.0,1.0,0.003897,0.057826,0.013084,0.008752,-0.087067,0.207973,0.194019,0.565885,2.58896,0.011761,5.0,9.0,0.0,800000011.0,0.0,14.34030,13183.0,289.0,7.0,0.057694,-5.534510e-14,0.009083,11.9225,13.3301,1.40766,0.007856,0.006228,-0.074405,0.093853,0.164150,-0.503280,4.42583,0.0,0.0,0.0,800000011.0,80000.0,80000.0,80.0,81.0,0.0,11.30220,14008.0,12.5,28.0,28.0,28.0,36000.0,0.000189,-1.512020e-15,0.057826,0.852936,206.8970,95.8380,0.000100,-0.020454,0.020427,0.042482,-0.016165,4.53250,0.000093,-0.000528,-0.000082,-0.000111,-5.506530e-06,-0.000329,-0.000325,-0.000312,-0.000286,-0.000245,-0.000190,-0.000134,-0.000114,-0.000141,-0.000164,0.0,0.0,0.0,0.0,801000011.0,0.0,11.05330,13215.0,70.0,4.0,0.0,0.0,7.983960,7.652170
2024-08-22 00:45:00,0.024721,1.16619,1180.31,1012.11,0.0,1.0,-1.064200,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,35976.0,0.0,0.005584,2447.96,2418.92,1.5,1.5,1.5,1.2,1.8,2.44274,2.41129,2.48162,0.052564,0.261365,2.59807,-0.000125,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,12.19690,18266.0,33.0,0.507978,2.41886,0.339024,47.4354,0.95,3.0,235.021,235.042,94.3960,1.15717,0.025031,0.0,0.0,0.34,36000.0,0.003369,0.000957,0.002922,0.002922,0.002922,1.15302,0.063739,1.0,36000.0,35976.0,35976.0,0.051992,21.14000,0.356024,0.014764,10.141500,0.779504,1.242240e-13,2.428350e-11,3.403420e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.045092,18.177100,0.316176,0.045092,18.177100,0.316176,0.045092,18.177100,0.316176,1.15302,1.16300,1.12603,0.063739,0.020380,0.017867,0.697558,1.675730,1.12861,34.0,55.0,77.0,3.0,4.0,5.0,1.0,1.0,1.0,0.0,360.0,35976.0,35976.0,-2.466670,1.408250,1.0,28.5628,12.5292,12.3742,1.65,1.65,1.65,1.4,3.0,11.8567,11.7838,11.9403,0.120380,0.073770,2.95287,0.001445,-0.000100,-2.25805,-2.25805,-2.371280,1.04023,1.0,0.0,1.0,0.0,800000000.0,1.6,5.65845,18259.0,0.046780,1.734820,38.0,3.0,1.0,11.0,4.445,4.445,4.445,9999.0,9999.0,35976.0,2.317860,0.658207,2.010240,2.010240,2.010240,1.15302,0.063739,1.0,12.966000,13.619900,0.433227,0.433227,0.433227,1.0,35976.0,0.0,0.000783,343.090,339.021,1.4,1.4,1.4,1.0,1.8,0.342644,0.339738,0.345821,0.004130,0.736501,3.66200,0.0,0.0,0.0,0.0,800000111.0,1.35,5.80783,18276.0,7.0,6.0,95.5790,6.10849,90.1333,325.6390,-0.647087,0.08,0.02,0.1,0.1,0.1,0.0,35976.0,-0.310596,-0.190357,-0.000277,-0.004270,4.020860,0.009007,0.007735,2473960.0,0.0,4.0,2.024082e+11,35976.0,35976.0,-0.006103,0.002613,0.168278,-0.028889,18.0501,11.0433,9.45399,18.10,17.89,18.23,0.269874,-0.767554,3.86893,-0.005946,-0.006103,-0.006103,45.1514,1.02645,2.0,3.0,0.0,800000001.0,0.0,25.93850,17185.0,0.004837,0.660857,44.0,327.0,3.0,7.0,1.0,1.0,0.112735,0.136575,0.072340,0.308109,-0.351551,0.485051,0.451541,-0.470765,1.92400,0.071402,1.0,2.0,0.0,800000011.0,0.0,6.37583,4874.0,83.0,5.0,-0.077080,1.168990e-14,0.009020,11.8303,13.1253,1.29503,0.007795,-0.045800,-0.272969,0.212019,0.357697,0.427838,2.27362,0.0,0.0,0.0,800000111.0,80111.0,80111.0,80.0,81.0,0.0,6.54785,6289.0,12.5,28.0,28.0,28.0,35976.0,-0.001542,4.349150e-15,0.136575,1.274790,335.9810,81.7847,0.003576,-0.043812,0.044498,0.068698,-0.147876,3.55408,-0.004007,-0.001913,0.001115,0.000455,7.914060e-06,-0.001549,-0.001530,-0.001487,-0.001417,-0.001305,-0.001150,-0.000960,-0.000753,-0.000531,-0.000315,0.0,0.0,0.0,0.0,800000011.0,0.0,8.77230,4874.0,44.0,3.0,0.0,0.0,0.130341,0.124083
2024-08-22 01:15:00,0.024713,1.16655,1180.66,1012.10,0.0,1.0,-0.916917,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.005392,2363.68,2335.95,1.5,1.5,1.5,1.2,1.8,2.35404,2.31723,2.42419,0.051332,0.203086,1.58076,0.000077,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,6.75808,18262.0,33.0,0.507556,2.33600,0.338731,47.4394,0.95,3.0,235.042,235.062,94.3750,1.15754,0.025023,0.0,0.0,0.34,36000.0,0.003349,0.000989,0.002838,0.002838,0.002838,1.17988,0.019744,1.0,36000.0,36000.0,36000.0,0.051675,-26.38320,-0.011653,0.015263,11.533600,0.107261,1.293530e-13,2.444880e-11,3.545280e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.043796,-22.026500,-0.010329,0.043796,-22.026500,-0.010329,0.043796,-22.026500,-0.010329,1.17988,1.19779,1.12821,0.019744,0.002304,0.008599,1.271920,1.110390,0.96930,14.0,70.0,5655.0,1.0,4.0,9.0,1.0,1.0,2.0,0.0,360.0,36000.0,36000.0,-2.112620,1.746000,1.0,28.5286,12.5136,12.3590,1.65,1.65,1.65,1.4,3.0,11.7233,11.6500,11.8038,0.110948,0.312269,2.79051,-0.001145,-0.000131,-1.93139,-1.93139,-2.042370,1.03439,4.0,0.0,7.0,0.0,800000001.0,1.6,5.73281,18252.0,0.093602,0.894161,16.0,2.0,1.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,2.304040,0.680537,1.952770,1.952770,1.952770,1.17988,0.019744,1.0,17.116100,18.170100,0.433214,0.433214,0.433214,1.0,36000.0,0.0,0.000782,342.752,338.732,1.4,1.4,1.4,1.0,1.8,0.342189,0.340088,0.344678,0.003767,1.217380,5.92224,0.0,0.0,0.0,0.0,800000111.0,1.35,6.41582,18265.0,7.0,6.0,95.5563,6.10839,90.9233,52.5350,0.738498,0.08,0.02,0.1,0.1,0.1,0.0,36000.0,-0.204166,-0.030438,-0.000044,-0.000683,-3.730510,-0.012993,0.007725,2474330.0,0.0,4.0,2.024082e+11,36000.0,36000.0,0.006626,0.002558,0.119491,-0.023742,17.9694,10.8900,9.43221,17.96,17.80,18.10,0.289831,0.547945,4.44402,0.006495,0.006626,0.006626,45.1372,1.02016,3.0,7.0,0.0,800000011.0,0.0,54.66370,16599.0,0.029842,0.914796,22.0,421.0,2.0,7.0,1.0,1.0,0.156042,0.256552,0.075366,0.135091,-0.003119,0.504048,0.399707,0.720652,2.73252,0.074618,1.0,2.0,0.0,800000011.0,0.0,7.22268,4637.0,56.0,4.0,0.203615,-5.091270e-14,0.009012,11.8129,12.9922,1.17926,0.007785,0.013951,-0.218836,0.216103,0.270052,-0.017194,2.30402,3.0,5.0,0.0,800000011.0,80100.0,80100.0,80.0,81.0,0.0,7.67300,5870.0,12.5,28.0,28.0,28.0,36000.0,0.003307,4.534160e-15,0.256552,1.421090,249.7910,74.5736,0.001305,-0.050907,0.050263,0.079303,-0.151094,4.06894,0.005093,-0.001636,0.001082,-0.000551,-2.584480e-07,-0.001576,-0.001545,-0.001472,-0.001341,-0.001139,-0.000873,-0.000577,-0.000298,-0.000065,0.000078,0.0,0.0,0.0,0.0,800000011.0,0.0,8.56235,4637.0,38.0,3.0,0.0,0.0,0.098737,0.093010
2024-08-22 01:45:00,0.024706,1.16689,1181.00,1012.09,0.0,1.0,5.929380,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.005279,2314.40,2287.27,1.5,1.5,1.5,1.2,1.8,2.32188,2.29739,2.33233,0.024348,-0.778327,2.65709,0.000016,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,8.89159,18233.0,33.0,0.506778,2.28727,0.337019,47.4380,0.95,3.0,235.062,235.083,94.3453,1.15787,0.025015,0.0,0.0,0.34,36000.0,-0.001216,0.001137,-0.000868,-0.000868,-0.000868,1.40045,0.012933,0.0,36000.0,36000.0,36000.0,-0.018765,9.28833,1.476980,0.017550,4.334050,0.457078,-7.675870e-14,-1.419690e-11,-2.091840e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.013400,6.439770,1.164720,-0.013400,6.439770,1.164720,-0.013399,6.439770,1.164720,1.40045,1.44234,1.26810,0.012933,0.000763,0.004559,0.553391,1.384320,1.22007,20.0,13.0,27.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,360.0,36000.0,36000.0,-4.961920,1.163070,1.0,28.5415,12.5215,12.3666,1.65,1.65,1.65,1.4,3.0,11.7135,11.6461,11.7911,0.110570,0.322935,3.22789,-0.000976,-0.000064,-4.70860,-4.70860,-4.653790,1.06621,8.0,0.0,15.0,0.0,800000001.0,1.6,5.75397,18220.0,0.059280,1.387860,7.0,1.0,0.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,-0.836837,0.782627,-0.597548,-0.597548,-0.597548,1.40045,0.012933,0.0,3.430510,3.445690,0.433287,0.433287,0.433287,1.0,36000.0,0.0,0.000778,341.016,337.018,1.4,1.4,1.4,1.0,1.8,0.340519,0.339047,0.342420,0.002718,1.030340,4.28390,0.0,0.0,0.0,0.0,800000011.0,1.35,6.06567,18241.0,7.0,6.0,95.5270,6.10733,91.9867,316.5150,-0.042208,0.08,0.02,0.1,0.1,0.1,0.0,36000.0,-0.226424,0.015374,0.000022,0.000345,-2.189390,-0.077053,0.007730,2474730.0,0.0,4.0,2.024082e+11,36000.0,36000.0,-0.004011,0.001851,0.074178,-0.071658,17.6770,10.7200,9.43686,17.70,17.58,17.80,0.220169,0.274345,9.89008,-0.003885,-0.004011,-0.004011,45.1357,1.03251,15.0,23.0,0.0,800001111.0,0.0,173.22600,14722.0,0.000106,1.829110,24.0,90.0,2.0,5.0,1.0,1.0,0.414759,0.571641,0.058632,0.592317,0.339238,0.785524,0.276100,-0.271776,2.45593,0.057702,2.0,2.0,0.0,800000111.0,0.0,8.62420,1967.0,35.0,3.0,-0.393380,-7.786270e-14,0.009020,11.8166,12.8460,1.02940,0.007790,-0.030265,-0.191912,0.169595,0.258089,0.400231,2.58092,8.0,12.0,0.0,800000001.0,80011.0,80011.0,80.0,81.0,0.0,6.61176,3306.0,12.5,28.0,28.0,28.0,36000.0,-0.000421,-2.689370e-15,0.571641,1.326420,332.6240,32.7773,0.000364,-0.039796,0.040488,0.074264,0.047252,5.37493,-0.002350,-0.003987,-0.000331,0.000161,2.913610e-05,-0.003879,-0.003838,-0.003747,-0.003604,-0.003402,-0.003134,-0.002837,-0.002483,-0.002005,-0.001485,4.0,0.0,11.0,0.0,800000111.0,0.0,10.41660,2151.0,27.0,2.0,0.0,0.0,0.492638,0.490468
2024-08-22 02:15:00,0.024722,1.16615,1180.25,1012.09,0.0,1.0,-184.813000,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,36000.0,0.0,0.005349,2345.44,2318.01,1.5,1.5,1.5,1.2,1.8,2.34334,2.33547,2.35410,0.017000,0.133115,4.11721,-0.000005,0.0,0.0,0.0,0.0,0.0,800000011.0,1.45,6.85446,18245.0,33.0,0.507028,2.31800,0.336307,47.4300,0.95,3.0,235.083,235.104,94.3202,1.15715,0.025031,0.0,0.0,0.34,36000.0,0.000018,0.000311,0.000017,0.000017,0.000017,1.07136,0.028684,2.0,36000.0,36000.0,36000.0,0.000273,1.89300,1.049310,0.004801,2.064620,0.560318,-1.195460e-14,-2.243670e-12,-3.255200e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000255,1.752430,1.004000,0.000255,1.752430,1.004000,0.000255,1.752430,1.004000,1.07136,1.08021,1.04513,0.028684,0.018979,0.019662,1.404230,2.054750,1.93307,2541.0,2.0,32.0,9.0,1.0,3.0,2.0,0.0,1.0,0.0,360.0,36000.0,36000.0,-2.252340,1.395160,1.0,28.5000,12.5052,12.3508,1.65,1.65,1.65,1.4,3.0,11.6888,11.6234,11.7595,0.102655,0.120663,2.99311,-0.000144,-0.000134,-2.04334,-2.04334,-2.035990,1.10627,4.0,0.0,8.0,0.0,800000001.0,1.6,5.88833,18232.0,0.036715,2.076200,37.0,3.0,1.0,11.0,4.445,4.445,4.445,9999.0,9999.0,36000.0,0.012187,0.214076,0.011375,0.011375,0.011375,1.07136,0.028684,2.0,1.712730,1.743740,0.433360,0.433360,0.433360,1.0,36000.0,0.0,0.000776,340.285,336.306,1.4,1.4,1.4,1.0,1.8,0.339329,0.337783,0.341581,0.003746,1.770780,7.16215,0.0,0.0,0.0,0.0,800000111.0,1.35,6.00034,18249.0,7.0,6.0,95.5000,6.10658,91.2333,287.8730,-0.986997,0.08,0.02,0.1,0.1,0.1,0.0,36000.0,0.133106,-0.031790,-0.000046,-0.000713,1.381850,-0.031998,0.007720,2474490.0,0.0,4.0,2.024082e+11,36000.0,36000.0,-0.001490,0.001419,0.082875,-0.053381,17.9999,10.8200,9.41358,18.01,17.82,18.21,0.295208,-0.188272,3.07115,-0.001413,-0.001490,-0.001490,45.1500,1.05439,2.0,4.0,0.0,800000011.0,0.0,25.87040,19082.0,0.016031,0.908108,5.0,320.0,1.0,7.0,2.0,1.0,0.042843,0.139619,0.035749,0.133291,-0.096264,0.357825,0.291011,0.056326,2.28051,0.034815,0.0,0.0,0.0,800000111.0,0.0,10.10000,7094.0,122.0,6.0,-0.132861,-1.783520e-14,0.009003,11.7982,12.9318,1.13369,0.007780,-0.025693,-0.218728,0.239778,0.277393,0.202095,2.06473,0.0,0.0,0.0,800000011.0,80011.0,80011.0,80.0,81.0,0.0,9.36540,8336.0,12.5,28.0,28.0,28.0,36000.0,-0.002405,-4.194610e-16,0.139619,0.953887,21.0018,80.9662,-0.000522,-0.035809,0.035217,0.064155,-0.017402,5.48936,-0.001205,-0.001731,0.000006,0.000044,2.513110e-05,-0.002013,-0.002003,-0.001982,-0.001935,-0.001849,-0.001724,-0.001579,-0.001389,-0.001133,-0.000899,0.0,0.0,0.0,0.0,800000111.0,0.0,8.74450,7094.0,2.0,1.0,0.0,0.0,0.986727,0.969184

# Save to file

In [11]:
OUTNAME = "32.1_CH-TAN_LGR_Level-1_eddypro_fluxnet"
filepath = save_parquet(filename=OUTNAME, data=df_reduced)

Saved file 32.1_CH-TAN_LGR_Level-1_eddypro_fluxnet.parquet (0.382 seconds).

# **End of notebook**.

In [12]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-10-06 15:22:06