# Imports

In [1]:
import importlib.metadata
import pandas as pd
import warnings
from datetime import datetime
from pathlib import Path

from diive.core.io.filereader import search_files, MultiDataFileReader
from diive.core.io.files import save_parquet, load_parquet
# pd.options.display.width = None
# pd.options.display.max_columns = None
pd.set_option('display.max_rows', 3000)
pd.set_option('display.max_columns', 3000)
warnings.filterwarnings(action='ignore', category=FutureWarning)
warnings.filterwarnings(action='ignore', category=UserWarning)
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
version_diive = importlib.metadata.version("diive")
print(f"diive version: v{version_diive}")

diive version: v0.89.0

# Load data: fluxes L1

In [2]:
irga = load_parquet(filepath="31.1_CH-TAN_IRGA_Level-1_eddypro_fluxnet.parquet")
lgr = load_parquet(filepath="32.1_CH-TAN_LGR_Level-1_eddypro_fluxnet.parquet")

Loaded .parquet file 31.1_CH-TAN_IRGA_Level-1_eddypro_fluxnet.parquet (0.098 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

Loaded .parquet file 32.1_CH-TAN_LGR_Level-1_eddypro_fluxnet.parquet (0.062 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# Merge files

## Start with IRGA data

In [3]:
df = irga.copy()
df

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_HEIGHT_SA,BADM_SA_OFFSET_NORTH,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,CUSTOM_FILTER_NR,CO2_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CO2_SPIKE_NREX,CO2_ABSLIM_NREX,CO2_VM97_TEST,CO2_LGD,CO2_KID,CO2_ZCD,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_H2O_MEAN,CUSTOM_CO2_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_FLOWRATE_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILE_NR,FC_NR,FC,FH2O,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FC_VADV,FH2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FC_STAGE1,FH2O_STAGE1,FC_STAGE2,FH2O_STAGE2,FC_SCF,FH2O_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FC_NSR,FH2O_NSR,FC_SS,FH2O_SS,FC_SS_TEST,FH2O_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H_UNCORR,H_STAGE1,H_STAGE2,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,RH_EP,ROT_YAW,ROT_PITCH,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-08-22 00:15:00,0.024738,1.16533,1179.50,1012.16,0.0,1.0,5.43736,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2670,-16.0,2.0,-2.5,100.0,9.5,13.2670,36000.0,35988.0,0.0,20.2703,510.948,504.612,1.25,1.25,1.3,1.2,1.4,508.578,503.942,516.814,13.20010,0.482800,3.11027,-0.044624,0.0,0.0,0.0,0.0,0.0,801000000.0,1.20,29.65330,96.0,26.0,0.0,8191.0,100.05,498.813,20.2993,95560.2,1.97733,0.000221,235.000,235.021,94.3978,1.15624,0.025051,0.0,0.0,0.34,36000.0,-0.000241,0.000326,-0.000115,-0.000115,-0.000115,2.08845,0.039353,2.0,36000.0,35988.0,-5.362070,-0.003715,1.468070,0.005038,-3.064910e-11,-7.573500e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.595330,-0.001779,-2.595330,-0.001779,-2.595330,-0.001779,2.06604,2.08845,0.137639,0.039353,1.861140,1.054360,102.0,279.0,6.0,7.0,2.0,2.0,0.0,360.0,35988.0,36000.0,-0.90021,0.535394,0.0,500.886,12.6266,12.4692,4.00,1.4,1.4,1.25,4.0,12.5540,12.519,12.588,0.042430,0.094386,2.01458,-0.62235,-0.62235,-0.615054,1.46363,0.0,0.0,0.0,0.0,801000111.0,1.35,2.96367,3915.0,0.256603,1.550550,35.0,3.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,-0.165560,0.224537,-0.079274,-0.079274,-0.079274,2.08845,0.039353,2.0,0.210249,0.220852,0.024894,0.024894,1.0,9.0,6.0,95.5900,95.0228,89.4400,86.1362,0.187709,0.08,0.02,0.1,0.1,0.0,36000.0,-0.607464,-0.076551,-0.000111,1.007300,-0.001718,0.007794,2473410.0,0.0,4.0,2.024082e+11,36000.0,36000.0,0.000200,0.000739,0.033197,-0.058330,18.2941,11.2767,9.56948,18.30,18.18,18.38,0.197375,0.570364,4.50305,0.000161,0.000200,0.000200,11.3720,1.23773,3.0,7.0,0.0,800000011.0,0.0,25.41780,23953.0,0.047729,0.781083,128.0,422.0,6.0,7.0,2.0,2.0,0.003897,0.057826,0.013084,0.008752,-0.087067,0.207973,0.194019,0.565885,2.58896,0.011761,5.0,9.0,0.0,800000011.0,0.0,14.34030,13183.0,289.0,7.0,0.057694,-5.534510e-14,0.009083,11.9225,13.3301,1.40766,0.007856,0.006228,-0.074405,0.093853,0.164150,-0.503280,4.42583,0.0,0.0,0.0,800000011.0,80100.0,80100.0,80.0,81.0,0.0,11.30220,14008.0,12.5,12.7,12.7,36000.0,0.000189,-1.512020e-15,0.057826,0.852936,206.8970,95.8380,0.000100,-0.020454,0.020427,0.042482,-0.016165,4.53250,0.000093,-0.000528,-0.065015,-0.000045,-0.000329,-0.000325,-0.000312,-0.000286,-0.000245,-0.000190,-0.000134,-0.000114,-0.000141,-0.000164,0.0,0.0,0.0,0.0,801000011.0,0.0,11.05330,13215.0,70.0,4.0,0.0,0.0,8.038090,7.652170
2024-08-22 00:45:00,0.024721,1.16619,1180.31,1012.11,0.0,1.0,-1.33447,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2624,-16.0,2.0,-2.5,100.0,9.5,13.2624,36000.0,35964.0,0.0,20.6208,519.320,512.896,1.30,1.30,1.3,1.2,1.4,517.297,502.074,535.721,17.97880,0.154933,1.68523,-0.133184,1.0,0.0,0.0,2.0,0.0,801000001.0,1.25,38.34520,68.0,26.0,0.0,8191.0,100.05,497.928,20.6465,95552.7,1.97432,0.000221,235.021,235.042,94.3960,1.15717,0.025031,0.0,0.0,0.34,36000.0,0.002663,0.000840,0.002429,0.002429,0.002429,1.09653,0.064482,1.0,36000.0,35964.0,1.344980,0.041102,3.661990,0.012962,8.968300e-11,2.163690e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.259390,0.037484,1.259390,0.037484,1.259390,0.037484,1.06796,1.09653,0.013650,0.064482,0.450948,1.089220,150.0,48.0,6.0,3.0,2.0,1.0,0.0,360.0,35964.0,35976.0,-2.44523,1.408250,0.0,497.497,12.5292,12.3742,1.25,1.4,1.4,1.25,4.0,12.5370,12.482,12.570,0.067429,-0.318367,2.52321,-2.25805,-2.25805,-2.350670,1.04023,0.0,0.0,0.0,0.0,801000011.0,1.35,2.95668,4019.0,0.046780,1.734820,38.0,3.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35964.0,1.832360,0.577841,1.671050,1.671050,1.671050,1.09653,0.064482,1.0,13.079700,13.619900,0.024873,0.024873,1.0,9.0,6.0,95.5790,95.0185,90.1333,325.6390,-0.647087,0.08,0.02,0.1,0.1,0.0,35976.0,-0.310596,-0.190833,-0.000277,0.373248,-0.004281,0.007735,2473960.0,0.0,4.0,2.024082e+11,35976.0,35976.0,-0.006103,0.002613,0.168278,-0.028638,18.0501,11.0433,9.45399,18.10,17.89,18.23,0.269874,-0.767554,3.86893,-0.005946,-0.006103,-0.006103,11.1148,1.02645,2.0,3.0,0.0,800000001.0,0.0,25.93850,17185.0,0.004837,0.660857,44.0,327.0,3.0,7.0,1.0,2.0,0.112735,0.136575,0.072340,0.308109,-0.351551,0.485051,0.451541,-0.470765,1.92400,0.071402,1.0,2.0,0.0,800000011.0,0.0,6.37583,4874.0,83.0,5.0,-0.077080,1.168990e-14,0.009020,11.8303,13.1253,1.29503,0.007795,-0.045800,-0.272969,0.212019,0.357697,0.427838,2.27362,0.0,0.0,0.0,800000111.0,80000.0,80000.0,80.0,81.0,0.0,6.54785,6289.0,12.5,12.7,12.7,35976.0,-0.001542,4.349150e-15,0.136575,1.274790,335.9810,81.7847,0.003576,-0.043812,0.044498,0.068698,-0.147876,3.55408,-0.004007,-0.001913,0.031523,0.000938,-0.001549,-0.001530,-0.001487,-0.001417,-0.001305,-0.001150,-0.000960,-0.000753,-0.000531,-0.000315,0.0,0.0,0.0,0.0,800000011.0,0.0,8.77230,4874.0,44.0,3.0,0.0,0.0,0.129208,0.124083
2024-08-22 01:15:00,0.024713,1.16655,1180.66,1012.10,0.0,1.0,-1.16190,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2808,-16.0,2.0,-2.5,100.0,9.5,13.2808,36000.0,35988.0,0.0,20.2247,509.222,502.983,1.20,1.30,1.3,1.2,1.4,508.978,500.990,517.227,10.85680,0.115552,3.27991,-0.199303,5.0,0.0,0.0,9.0,0.0,801000000.0,1.25,70.27110,60.0,26.0,0.0,8191.0,100.05,493.248,20.2501,95532.5,1.97320,0.000221,235.042,235.062,94.3750,1.15754,0.025023,0.0,0.0,0.34,36000.0,0.002601,0.000851,0.002076,0.002076,0.002076,1.25324,0.000903,1.0,36000.0,35988.0,-0.439665,0.040143,0.965964,0.013127,9.170200e-11,2.253240e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.369339,0.032032,-0.369339,0.032032,-0.369339,0.032032,1.19041,1.25324,0.020090,0.000903,1.042770,1.307430,568.0,16.0,8.0,2.0,2.0,1.0,0.0,360.0,35988.0,36000.0,-2.07966,1.746000,0.0,496.948,12.5136,12.3590,1.25,1.4,1.4,1.25,4.0,12.3940,12.356,12.454,0.058973,0.228152,2.04465,-1.93139,-1.93139,-2.010520,1.03439,0.0,0.0,0.0,0.0,801000011.0,1.35,2.91301,4018.0,0.093602,0.894161,16.0,2.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,1.789880,0.585304,1.428210,1.428210,1.428210,1.25324,0.000903,1.0,17.387300,18.170100,0.024870,0.024870,1.0,9.0,6.0,95.5563,94.9990,90.9233,52.5350,0.738498,0.08,0.02,0.1,0.1,0.0,36000.0,-0.204166,-0.030514,-0.000044,-0.446782,-0.000684,0.007725,2474330.0,0.0,4.0,2.024082e+11,36000.0,36000.0,0.006626,0.002558,0.119491,-0.023372,17.9694,10.8900,9.43221,17.96,17.80,18.10,0.289831,0.547945,4.44402,0.006495,0.006626,0.006626,11.0214,1.02016,3.0,7.0,0.0,800000011.0,0.0,54.66370,16599.0,0.029842,0.914796,22.0,421.0,2.0,7.0,1.0,2.0,0.156042,0.256552,0.075366,0.135091,-0.003119,0.504048,0.399707,0.720652,2.73252,0.074618,1.0,2.0,0.0,800000011.0,0.0,7.22268,4637.0,56.0,4.0,0.203615,-5.091270e-14,0.009012,11.8129,12.9922,1.17926,0.007785,0.013951,-0.218836,0.216103,0.270052,-0.017194,2.30402,3.0,5.0,0.0,800000011.0,80000.0,80000.0,80.0,81.0,0.0,7.67300,5870.0,12.5,12.7,12.7,36000.0,0.003307,4.534160e-15,0.256552,1.421090,249.7910,74.5736,0.001305,-0.050907,0.050263,0.079303,-0.151094,4.06894,0.005093,-0.001636,-0.009242,0.000802,-0.001576,-0.001545,-0.001472,-0.001341,-0.001139,-0.000873,-0.000577,-0.000298,-0.000065,0.000078,0.0,0.0,0.0,0.0,800000011.0,0.0,8.56235,4637.0,38.0,3.0,0.0,0.0,0.097197,0.093010
2024-08-22 01:45:00,0.024706,1.16689,1181.00,1012.09,0.0,1.0,12.55270,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2492,-16.0,2.0,-2.5,100.0,9.5,13.2492,36000.0,35988.0,0.0,20.3782,512.958,506.673,1.20,1.30,1.3,1.2,1.4,511.588,506.852,517.399,8.37740,0.507629,4.92329,-0.199634,6.0,0.0,0.0,12.0,0.0,801000000.0,1.25,32.16500,61.0,26.0,0.0,8191.0,100.05,493.388,20.4039,95504.6,1.97145,0.000221,235.062,235.083,94.3453,1.15787,0.025015,0.0,0.0,0.34,36000.0,-0.000577,0.000609,-0.000442,-0.000442,-0.000442,1.30524,0.000996,1.0,36000.0,35988.0,6.399870,-0.008908,1.585380,0.009404,-3.636370e-11,-8.875450e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.517460,-0.006825,5.517460,-0.006825,5.517460,-0.006825,1.15993,1.30524,0.018288,0.000996,1.197390,0.817492,9.0,36.0,1.0,3.0,0.0,1.0,0.0,360.0,35988.0,36000.0,-4.98663,1.163420,0.0,497.380,12.5215,12.3666,3.90,3.9,1.4,1.25,4.0,12.4040,12.375,12.443,0.041982,-0.342920,2.26577,-4.71404,-4.71404,-4.676990,1.06620,0.0,0.0,0.0,0.0,801000011.0,3.85,2.92740,3969.0,0.059305,1.389220,7.0,1.0,0.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,-0.397256,0.419351,-0.304354,-0.304354,-0.304354,1.30524,0.000996,1.0,3.417960,3.446220,0.024864,0.024864,1.0,9.0,6.0,95.5270,94.9717,91.9867,316.5150,-0.042765,0.08,0.02,0.1,0.1,0.0,36000.0,-0.226424,0.015412,0.000022,0.166366,0.000346,0.007730,2474730.0,0.0,4.0,2.024082e+11,36000.0,36000.0,-0.004015,0.001852,0.074181,-0.071984,17.6770,10.7200,9.43686,17.70,17.58,17.80,0.220169,0.274345,9.89008,-0.003889,-0.004015,-0.004015,10.8689,1.03251,15.0,23.0,0.0,800001111.0,0.0,173.22600,14722.0,0.001128,1.829450,24.0,90.0,2.0,5.0,1.0,2.0,0.414759,0.571641,0.058658,0.592317,0.339239,0.785525,0.276100,-0.271783,2.45593,0.057727,2.0,2.0,0.0,800000111.0,0.0,8.62409,1967.0,35.0,3.0,-0.393381,-1.261010e-13,0.009020,11.8166,12.8460,1.02940,0.007790,-0.030265,-0.191911,0.169596,0.258090,0.400223,2.58091,7.0,10.0,0.0,800000001.0,81000.0,81000.0,80.0,81.0,0.0,6.61147,3306.0,12.5,12.7,12.7,36000.0,-0.000427,-1.784440e-15,0.571641,1.326420,332.6240,32.7774,0.000369,-0.039793,0.040494,0.074303,0.036146,5.47008,-0.002352,-0.003992,0.138022,-0.000171,-0.003884,-0.003844,-0.003753,-0.003609,-0.003407,-0.003139,-0.002840,-0.002485,-0.002006,-0.001487,3.0,0.0,8.0,0.0,800000111.0,0.0,10.41040,2150.0,27.0,2.0,0.0,0.0,0.494448,0.490393
2024-08-22 02:15:00,0.024722,1.16615,1180.25,1012.09,0.0,1.0,-6.50613,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2581,-16.0,2.0,-2.5,100.0,9.5,13.2581,36000.0,35988.0,0.0,19.8573,499.804,493.697,1.40,1.30,1.3,1.2,1.4,497.863,492.281,505.274,11.31780,0.982458,4.29494,-0.329740,13.0,0.0,0.0,28.0,0.0,801000100.0,1.25,74.72630,65.0,26.0,0.0,8191.0,100.05,492.047,19.8812,95480.3,1.97033,0.000221,235.083,235.104,94.3202,1.15715,0.025031,0.0,0.0,0.34,36000.0,0.000507,0.000417,0.000376,0.000376,0.000376,1.34680,0.023643,1.0,36000.0,35988.0,4.241850,0.007820,1.852140,0.006438,-8.329360e-12,-2.083740e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.242020,0.005807,3.242020,0.005807,3.242020,0.005807,1.30840,1.34680,0.005463,0.023643,2.268170,1.492010,33.0,66.0,3.0,4.0,1.0,1.0,0.0,360.0,35988.0,36000.0,-2.26875,1.395130,0.0,496.767,12.5052,12.3508,1.25,1.4,1.4,1.25,4.0,12.3710,12.343,12.397,0.046730,-0.218886,3.66862,-2.04315,-2.04315,-2.050830,1.10626,0.0,0.0,0.0,0.0,801000011.0,1.35,3.00004,3980.0,0.036603,2.076450,37.0,3.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,0.348709,0.287083,0.258917,0.258917,0.258917,1.34680,0.023643,1.0,1.700340,1.743900,0.024862,0.024862,1.0,9.0,6.0,95.5000,94.9459,91.2333,287.8730,-0.986997,0.08,0.02,0.1,0.1,0.0,36000.0,0.133106,-0.031870,-0.000046,-0.584678,-0.000715,0.007720,2474490.0,0.0,4.0,2.024082e+11,36000.0,36000.0,-0.001490,0.001419,0.082875,-0.053770,17.9999,10.8200,9.41358,18.01,17.82,18.21,0.295199,-0.188105,3.07074,-0.001413,-0.001490,-0.001490,10.7773,1.05439,10.0,16.0,0.0,800000011.0,0.0,25.88430,19096.0,0.016031,0.908108,5.0,320.0,1.0,7.0,2.0,2.0,0.042843,0.139619,0.035749,0.133291,-0.096264,0.357825,0.291011,0.056326,2.28051,0.034815,0.0,0.0,0.0,800000111.0,0.0,10.10000,7094.0,122.0,6.0,-0.132861,-1.783520e-14,0.009003,11.7982,12.9318,1.13369,0.007780,-0.025693,-0.218728,0.239778,0.277393,0.202095,2.06473,0.0,0.0,0.0,800000011.0,81000.0,81000.0,80.0,81.0,0.0,9.36540,8336.0,12.5,12.7,12.7,36000.0,-0.002405,-4.194610e-16,0.139619,0.953887,21.0018,80.9662,-0.000522,-0.035809,0.035217,0.064155,-0.017402,5.48936,-0.001205,-0.001731,0.081151,0.000145,-0.002012,-0.002003,-0.001981,-0.001935,-0.001848,-0.001724,-0.001579,-0.001389,-0.001133,-0.000899,0.0,0.0,0.0,0.0,800000111.0,0.0,8.74450,7094.0,2.0,1.0,0.0,0.0,0.993920,0.969094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-06-04 21:45:00,0.025243,1.14074,1156.61,1013.91,0.0,1.0,-3.76505,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,12.4224,-16.0,2.0,-2.5,100.0,9.5,12.4224,36000.0,35988.0,0.0,17.1765,442.914,436.493,1.30,1.30,1.3,1.2,1.4,442.826,442.015,443.705,1.22629,0.386751,2.99549,0.118291,2.0,0.0,0.0,4.0,0.0,801000000.0,1.25,7.41810,100.0,26.0,0.0,8190.0,93.38,570.003,17.1626,95055.1,2.07243,0.000207,155.896,155.917,93.6640,1.12971,0.025639,0.0,0.0,0.34,36000.0,0.014609,0.005058,0.008581,0.008581,0.008581,1.70249,0.002004,1.0,36000.0,35988.0,10.565800,0.225456,0.510651,0.078049,7.861890e-11,2.782380e-12,21.2662,-3.22723,7.30000,18.1780,27.7226,38.8814,46.5311,58.2514,7.813940,0.132427,7.813940,0.132427,7.813940,0.132427,1.35218,1.70249,0.013384,0.002004,1.169390,1.026990,8.0,52.0,1.0,4.0,0.0,1.0,0.0,360.0,35988.0,36000.0,-37.67390,2.051730,0.0,607.888,15.6902,15.4478,4.00,1.4,1.4,1.25,4.0,14.7350,14.613,14.829,0.153602,-0.408781,2.46340,-36.18860,-36.18860,-36.374200,1.03573,0.0,0.0,0.0,0.0,801000011.0,1.35,3.00245,4936.0,0.012405,1.418530,3.0,1.0,0.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,10.006200,3.463980,5.877390,5.877390,5.877390,1.70249,0.002004,1.0,157.648000,160.364000,0.025412,0.025412,1.0,9.0,6.0,95.1340,94.5840,82.7000,69.4056,1.589330,0.08,0.02,0.1,0.1,0.0,36000.0,-0.121744,-0.191570,-0.000280,0.012762,-0.004316,0.009667,2462940.0,0.0,4.0,2.025060e+11,36000.0,36000.0,-0.194661,0.014428,1.511860,-0.078851,21.8684,15.6933,12.72580,21.88,21.74,22.00,0.180460,-0.140716,2.65990,-0.191680,-0.194661,-0.194661,15.9523,1.01555,4.0,5.0,0.0,800000001.0,0.0,8.87289,5096.0,0.032799,1.410530,2.0,51.0,1.0,4.0,0.0,2.0,1.387710,3.946670,0.413091,3.849200,3.102920,4.687980,1.236280,0.556107,3.90710,0.409916,30.0,47.0,0.0,800000000.0,0.0,6.40734,2.0,12.0,1.0,3.693030,-4.836960e-14,0.011028,14.7001,17.7752,3.07511,0.009762,-0.020410,-0.698807,0.712354,1.103020,-0.009992,3.64680,25.0,42.0,0.0,800000000.0,81000.0,81000.0,80.0,80.0,0.0,6.46381,13.0,12.5,12.7,12.7,36000.0,0.109462,4.577120e-15,3.946670,10.557900,223.4950,15.4831,0.001967,-0.308308,0.313335,0.527908,-0.030854,4.24383,-0.165534,-0.031288,0.200341,0.003395,-0.031000,-0.028649,-0.025581,-0.022044,-0.018215,-0.014223,-0.010431,-0.007270,-0.004831,-0.003134,0.0,0.0,0.0,0.0,800000000.0,0.0,6.58389,2.0,5.0,1.0,0.0,0.0,0.010720,0.010538

## Add *new* columns from QCL LGR data

In [4]:
newcols = [c for c in lgr.columns if c not in df.columns]
df = pd.concat([df, lgr[newcols]], axis=1)
df

,AIR_MV,AIR_DENSITY,AIR_RHO_CP,AIR_CP,AOA_METHOD,AXES_ROTATION_METHOD,BOWEN,BURBA_METHOD,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_LOCATION_ELEV,BADM_HEIGHTC,BADM_INST_SAMPLING_INT,BADM_INST_AVERAGING_INT,BADM_INST_HEIGHT_SA,BADM_SA_OFFSET_NORTH,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,CUSTOM_FILTER_NR,CO2_NR,CO2_MEAS_TYPE,CO2_MOLAR_DENSITY,CO2_MIXING_RATIO,CO2,CO2_TLAG_ACTUAL,CO2_TLAG_USED,CO2_TLAG_NOMINAL,CO2_TLAG_MIN,CO2_TLAG_MAX,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_KUR,CO2_MEAS_H2O_MEAS_COV,CO2_NUM_SPIKES,CUSTOM_FILTER_NREX,CO2_DIAG_NREX,CO2_SPIKE_NREX,CO2_ABSLIM_NREX,CO2_VM97_TEST,CO2_LGD,CO2_KID,CO2_ZCD,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_H2O_MEAN,CUSTOM_CO2_MEAN,CUSTOM_AIR_P_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_FLOWRATE_MEAN,DOY_START,DOY_END,DRYAIR_PARTIAL_PRESSURE,DRYAIR_DENSITY,DRYAIR_MV,DETRENDING_METHOD,DENTRENDING_TIME_CONSTANT,DISPLACEMENT_HEIGHT,EXPECT_NR,ET,ET_RANDUNC_HF,ET_UNCORR,ET_STAGE1,ET_STAGE2,ET_SCF,ET_CORRDIFF,ET_SSITC_TEST,FILE_NR,FC_NR,FC,FH2O,FC_RANDUNC_HF,FH2O_RANDUNC_HF,FC_VADV,FH2O_VADV,FETCH_MAX,FETCH_OFFSET,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FC_UNCORR,FH2O_UNCORR,FC_STAGE1,FH2O_STAGE1,FC_STAGE2,FH2O_STAGE2,FC_SCF,FH2O_SCF,FC_CORRDIFF,FH2O_CORRDIFF,FC_NSR,FH2O_NSR,FC_SS,FH2O_SS,FC_SS_TEST,FH2O_SS_TEST,FC_SSITC_TEST,FH2O_SSITC_TEST,FOOTPRINT_MODEL,FILE_TIME_DURATION,H2O_NR,H_NR,H,H_RANDUNC_HF,H2O_MEAS_TYPE,H2O_MOLAR_DENSITY,H2O_MIXING_RATIO,H2O,H2O_TLAG_ACTUAL,H2O_TLAG_USED,H2O_TLAG_NOMINAL,H2O_TLAG_MIN,H2O_TLAG_MAX,H2O_MEAS_MEDIAN,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_KUR,H_UNCORR,H_STAGE1,H_STAGE2,H_SCF,H2O_NUM_SPIKES,H2O_DIAG_NREX,H2O_SPIKE_NREX,H2O_ABSLIM_NREX,H2O_VM97_TEST,H2O_LGD,H2O_KID,H2O_ZCD,H_CORRDIFF,H_NSR,H_SS,H_SS_TEST,H_SSITC_TEST,HPATH_SA,HPATH_GA_CO2,HPATH_GA_H2O,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE_NR,LE,LE_RANDUNC_HF,LE_UNCORR,LE_STAGE1,LE_STAGE2,LE_SCF,LE_CORRDIFF,LE_SSITC_TEST,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,NIGHT,NUM_CUSTOM_VARS,NUM_BIOMET_VARS,PA_EP,PA_CELL,RH_EP,ROT_YAW,ROT_PITCH,ROUGHNESS_LENGTH,RESPONSE_TIME_SA,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,SW_IN_POT,SONIC_NR,SH_SINGLE,SLE_SINGLE,SET_SINGLE,SC_SINGLE,SH2O_SINGLE,SPECIFIC_HUMIDITY,SPECIFIC_HEAT_EVAP,SONIC_DIAG_NREX,SPECTRAL_CORRECTION_METHOD,TIMESTAMP_START,T_SONIC_NR,TAU_NR,TAU,TAU_RANDUNC_HF,TKE,TSTAR,T_SONIC,TA_EP,TDEW,T_SONIC_MEDIAN,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_KUR,TAU_UNCORR,TAU_STAGE1,TAU_STAGE2,T_CELL,TAU_SCF,T_SONIC_NUM_SPIKES,T_SONIC_SPIKE_NREX,T_SONIC_ABSLIM_NREX,T_SONIC_VM97_TEST,T_SONIC_LGD,T_SONIC_KID,T_SONIC_ZCD,TAU_CORRDIFF,TAU_NSR,TAU_SS,T_SONIC_ITC,TAU_SS_TEST,T_SONIC_ITC_TEST,TAU_SSITC_TEST,TIMELAG_DETECTION_METHOD,U_UNROT,U,USTAR,U_MEDIAN,U_P25,U_P75,U_SIGMA,U_SKW,U_KUR,USTAR_UNCORR,U_NUM_SPIKES,U_SPIKE_NREX,U_ABSLIM_NREX,U_VM97_TEST,U_LGD,U_KID,U_ZCD,U_ITC,U_ITC_TEST,V_UNROT,V,VAPOR_DENSITY,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VPD_EP,VAPOR_DRYAIR_RATIO,V_MEDIAN,V_P25,V_P75,V_SIGMA,V_SKW,V_KUR,V_NUM_SPIKES,V_SPIKE_NREX,V_ABSLIM_NREX,V_VM97_TEST,VM97_TLAG_HF,VM97_TLAG_SF,VM97_AOA_HF,VM97_NSHW_HF,V_LGD,V_KID,V_ZCD,VPATH_SA,VPATH_GA_CO2,VPATH_GA_H2O,WD_FILTER_NR,W_UNROT,W,WS,WS_MAX,WD,WD_SIGMA,W_MEDIAN,W_P25,W_P75,W_SIGMA,W_SKW,W_KUR,W_U_COV,W_T_SONIC_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N1626,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0004,W_NUM_SPIKES,WD_FILTER_NREX,W_SPIKE_NREX,W_ABSLIM_NREX,W_VM97_TEST,W_LGD,W_KID,W_ZCD,W_ITC,W_ITC_TEST,WBOOST_APPLIED,WPL_APPLIED,ZL,ZL_UNCORR,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,CH4_NR,CH4_MEAS_TYPE,CH4_MOLAR_DENSITY,CH4_MIXING_RATIO,CH4,CH4_TLAG_ACTUAL,CH4_TLAG_USED,CH4_TLAG_NOMINAL,CH4_TLAG_MIN,CH4_TLAG_MAX,CH4_MEAS_MEDIAN,CH4_MEAS_P25,CH4_MEAS_P75,CH4_MEAS_SIGMA,CH4_MEAS_SKW,CH4_MEAS_KUR,CH4_MEAS_N2O_MEAS_COV,CH4_NUM_SPIKES,CH4_DIAG_NREX,CH4_SPIKE_NREX,CH4_ABSLIM_NREX,CH4_VM97_TEST,CH4_LGD,CH4_KID,CH4_ZCD,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_CH4_MEAN,CUSTOM_N2O_MEAN,CUSTOM_T_UNKNOWN_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_FIT_FLAG_MEAN,FCH4_NR,FN2O_NR,FCH4,FN2O,FCH4_RANDUNC_HF,FN2O_RANDUNC_HF,FCH4_VADV,FN2O_VADV,FCH4_UNCORR,FN2O_UNCORR,FCH4_STAGE1,FN2O_STAGE1,FCH4_STAGE2,FN2O_STAGE2,FCH4_SCF,FN2O_SCF,FCH4_CORRDIFF,FN2O_CORRDIFF,FCH4_NSR,FN2O_NSR,FCH4_SS,FN2O_SS,FCH4_SS_TEST,FN2O_SS_TEST,FCH4_SSITC_TEST,FN2O_SSITC_TEST,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_N2O_MEAS_COV,HPATH_GA_CH4,HPATH_GA_N2O,MV_AIR_CELL_CH4,MV_AIR_CELL_N2O,N2O_NR,N2O_MEAS_TYPE,N2O_MOLAR_DENSITY,N2O_MIXING_RATIO,N2O,N2O_TLAG_ACTUAL,N2O_TLAG_USED,N2O_TLAG_NOMINAL,N2O_TLAG_MIN,N2O_TLAG_MAX,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_KUR,N2O_NUM_SPIKES,N2O_DIAG_NREX,N2O_SPIKE_NREX,N2O_ABSLIM_NREX,N2O_VM97_TEST,N2O_LGD,N2O_KID,N2O_ZCD,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_N2O,SCH4_SINGLE,SN2O_SINGLE,VPATH_GA_CH4,VPATH_GA_N2O,W_CH4_MEAS_COV,W_N2O_MEAS_COV
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-08-22 00:15:00,0.024738,1.16533,1179.50,1012.16,0.0,1.0,5.43736,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2670,-16.0,2.0,-2.5,100.0,9.5,13.2670,36000.0,35988.0,0.0,20.2703,510.948,504.612,1.25,1.25,1.3,1.2,1.4,508.578,503.942,516.814,13.20010,0.482800,3.11027,-0.044624,0.0,0.0,0.0,0.0,0.0,801000000.0,1.20,29.65330,96.0,26.0,0.0,8191.0,100.05,498.813,20.2993,95560.2,1.97733,0.000221,235.000,235.021,94.3978,1.15624,0.025051,0.0,0.0,0.34,36000.0,-0.000241,0.000326,-0.000115,-0.000115,-0.000115,2.08845,0.039353,2.0,36000.0,35988.0,-5.362070,-0.003715,1.468070,0.005038,-3.064910e-11,-7.573500e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.595330,-0.001779,-2.595330,-0.001779,-2.595330,-0.001779,2.06604,2.08845,0.137639,0.039353,1.861140,1.054360,102.0,279.0,6.0,7.0,2.0,2.0,0.0,360.0,35988.0,36000.0,-0.90021,0.535394,0.0,500.886,12.6266,12.4692,4.00,1.4,1.4,1.25,4.0,12.5540,12.519,12.588,0.042430,0.094386,2.01458,-0.62235,-0.62235,-0.615054,1.46363,0.0,0.0,0.0,0.0,801000111.0,1.35,2.96367,3915.0,0.256603,1.550550,35.0,3.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,-0.165560,0.224537,-0.079274,-0.079274,-0.079274,2.08845,0.039353,2.0,0.210249,0.220852,0.024894,0.024894,1.0,9.0,6.0,95.5900,95.0228,89.4400,86.1362,0.187709,0.08,0.02,0.1,0.1,0.0,36000.0,-0.607464,-0.076551,-0.000111,1.007300,-0.001718,0.007794,2473410.0,0.0,4.0,2.024082e+11,36000.0,36000.0,0.000200,0.000739,0.033197,-0.058330,18.2941,11.2767,9.56948,18.30,18.18,18.38,0.197375,0.570364,4.50305,0.000161,0.000200,0.000200,11.3720,1.23773,3.0,7.0,0.0,800000011.0,0.0,25.41780,23953.0,0.047729,0.781083,128.0,422.0,6.0,7.0,2.0,2.0,0.003897,0.057826,0.013084,0.008752,-0.087067,0.207973,0.194019,0.565885,2.58896,0.011761,5.0,9.0,0.0,800000011.0,0.0,14.34030,13183.0,289.0,7.0,0.057694,-5.534510e-14,0.009083,11.9225,13.3301,1.40766,0.007856,0.006228,-0.074405,0.093853,0.164150,-0.503280,4.42583,0.0,0.0,0.0,800000011.0,80100.0,80100.0,80.0,81.0,0.0,11.30220,14008.0,12.5,12.7,12.7,36000.0,0.000189,-1.512020e-15,0.057826,0.852936,206.8970,95.8380,0.000100,-0.020454,0.020427,0.042482,-0.016165,4.53250,0.000093,-0.000528,-0.065015,-0.000045,-0.000329,-0.000325,-0.000312,-0.000286,-0.000245,-0.000190,-0.000134,-0.000114,-0.000141,-0.000164,0.0,0.0,0.0,0.0,801000011.0,0.0,11.05330,13215.0,70.0,4.0,0.0,0.0,8.038090,7.652170,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,0.0,0.005379,2357.52,2329.47,1.5,1.5,1.5,1.2,1.8,2.36592,2.34596,2.37736,0.029063,-1.426830,4.87225,0.000029,0.0,0.0,0.0,0.0,800000011.0,1.45,7.64521,18261.0,33.0,0.507556,2.32939,0.338817,47.4423,0.95,3.0,36000.0,36000.0,-5.38187,-0.262678,3.101760,0.461859,-8.132760e-12,-1.182910e-12,-4.441950,-0.219816,-4.441950,-0.219816,-4.441950,-0.219816,1.21160,1.19499,0.007094,0.154014,1.022570,2.13904,65.0,130.0,4.0,6.0,1.0,2.0,-0.000269,-0.000053,4.445,4.445,0.433087,0.433087,36000.0,0.0,0.000782,342.901,338.820,1.4,1.4,1.4,1.0,1.8,0.341617,0.339825,0.344971,0.004411,1.217000,4.22425,0.0,0.0,0.0,0.0,800000111.0,1.35,5.90357,18266.0,0.1,0.1,4.077140,0.191593,28.0,28.0,-0.000111,-5.506530e-06
2024-08-22 00:45:00,0.024721,1.16619,1180.31,1012.11,0.0,1.0,-1.33447,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2624,-16.0,2.0,-2.5,100.0,9.5,13.2624,36000.0,35964.0,0.0,20.6208,519.320,512.896,1.30,1.30,1.3,1.2,1.4,517.297,502.074,535.721,17.97880,0.154933,1.68523,-0.133184,1.0,0.0,0.0,2.0,0.0,801000001.0,1.25,38.34520,68.0,26.0,0.0,8191.0,100.05,497.928,20.6465,95552.7,1.97432,0.000221,235.021,235.042,94.3960,1.15717,0.025031,0.0,0.0,0.34,36000.0,0.002663,0.000840,0.002429,0.002429,0.002429,1.09653,0.064482,1.0,36000.0,35964.0,1.344980,0.041102,3.661990,0.012962,8.968300e-11,2.163690e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.259390,0.037484,1.259390,0.037484,1.259390,0.037484,1.06796,1.09653,0.013650,0.064482,0.450948,1.089220,150.0,48.0,6.0,3.0,2.0,1.0,0.0,360.0,35964.0,35976.0,-2.44523,1.408250,0.0,497.497,12.5292,12.3742,1.25,1.4,1.4,1.25,4.0,12.5370,12.482,12.570,0.067429,-0.318367,2.52321,-2.25805,-2.25805,-2.350670,1.04023,0.0,0.0,0.0,0.0,801000011.0,1.35,2.95668,4019.0,0.046780,1.734820,38.0,3.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35964.0,1.832360,0.577841,1.671050,1.671050,1.671050,1.09653,0.064482,1.0,13.079700,13.619900,0.024873,0.024873,1.0,9.0,6.0,95.5790,95.0185,90.1333,325.6390,-0.647087,0.08,0.02,0.1,0.1,0.0,35976.0,-0.310596,-0.190833,-0.000277,0.373248,-0.004281,0.007735,2473960.0,0.0,4.0,2.024082e+11,35976.0,35976.0,-0.006103,0.002613,0.168278,-0.028638,18.0501,11.0433,9.45399,18.10,17.89,18.23,0.269874,-0.767554,3.86893,-0.005946,-0.006103,-0.006103,11.1148,1.02645,2.0,3.0,0.0,800000001.0,0.0,25.93850,17185.0,0.004837,0.660857,44.0,327.0,3.0,7.0,1.0,2.0,0.112735,0.136575,0.072340,0.308109,-0.351551,0.485051,0.451541,-0.470765,1.92400,0.071402,1.0,2.0,0.0,800000011.0,0.0,6.37583,4874.0,83.0,5.0,-0.077080,1.168990e-14,0.009020,11.8303,13.1253,1.29503,0.007795,-0.045800,-0.272969,0.212019,0.357697,0.427838,2.27362,0.0,0.0,0.0,800000111.0,80000.0,80000.0,80.0,81.0,0.0,6.54785,6289.0,12.5,12.7,12.7,35976.0,-0.001542,4.349150e-15,0.136575,1.274790,335.9810,81.7847,0.003576,-0.043812,0.044498,0.068698,-0.147876,3.55408,-0.004007,-0.001913,0.031523,0.000938,-0.001549,-0.001530,-0.001487,-0.001417,-0.001305,-0.001150,-0.000960,-0.000753,-0.000531,-0.000315,0.0,0.0,0.0,0.0,800000011.0,0.0,8.77230,4874.0,44.0,3.0,0.0,0.0,0.129208,0.124083,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,35976.0,0.0,0.005584,2447.96,2418.92,1.5,1.5,1.5,1.2,1.8,2.44274,2.41129,2.48162,0.052564,0.261365,2.59807,-0.000125,0.0,0.0,0.0,0.0,800000011.0,1.45,12.19690,18266.0,33.0,0.507978,2.41886,0.339024,47.4354,0.95,3.0,35976.0,35976.0,21.14000,0.356024,10.141500,0.779504,2.428350e-11,3.403420e-12,18.177100,0.316176,18.177100,0.316176,18.177100,0.316176,1.16300,1.12603,0.020380,0.017867,1.675730,1.12861,55.0,77.0,4.0,5.0,1.0,1.0,0.001445,-0.000100,4.445,4.445,0.433227,0.433227,35976.0,0.0,0.000783,343.090,339.021,1.4,1.4,1.4,1.0,1.8,0.342644,0.339738,0.345821,0.004130,0.736501,3.66200,0.0,0.0,0.0,0.0,800000111.0,1.35,5.80783,18276.0,0.1,0.1,4.020860,0.009007,28.0,28.0,0.000455,7.914060e-06
2024-08-22 01:15:00,0.024713,1.16655,1180.66,1012.10,0.0,1.0,-1.16190,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2808,-16.0,2.0,-2.5,100.0,9.5,13.2808,36000.0,35988.0,0.0,20.2247,509.222,502.983,1.20,1.30,1.3,1.2,1.4,508.978,500.990,517.227,10.85680,0.115552,3.27991,-0.199303,5.0,0.0,0.0,9.0,0.0,801000000.0,1.25,70.27110,60.0,26.0,0.0,8191.0,100.05,493.248,20.2501,95532.5,1.97320,0.000221,235.042,235.062,94.3750,1.15754,0.025023,0.0,0.0,0.34,36000.0,0.002601,0.000851,0.002076,0.002076,0.002076,1.25324,0.000903,1.0,36000.0,35988.0,-0.439665,0.040143,0.965964,0.013127,9.170200e-11,2.253240e-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.369339,0.032032,-0.369339,0.032032,-0.369339,0.032032,1.19041,1.25324,0.020090,0.000903,1.042770,1.307430,568.0,16.0,8.0,2.0,2.0,1.0,0.0,360.0,35988.0,36000.0,-2.07966,1.746000,0.0,496.948,12.5136,12.3590,1.25,1.4,1.4,1.25,4.0,12.3940,12.356,12.454,0.058973,0.228152,2.04465,-1.93139,-1.93139,-2.010520,1.03439,0.0,0.0,0.0,0.0,801000011.0,1.35,2.91301,4018.0,0.093602,0.894161,16.0,2.0,1.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,1.789880,0.585304,1.428210,1.428210,1.428210,1.25324,0.000903,1.0,17.387300,18.170100,0.024870,0.024870,1.0,9.0,6.0,95.5563,94.9990,90.9233,52.5350,0.738498,0.08,0.02,0.1,0.1,0.0,36000.0,-0.204166,-0.030514,-0.000044,-0.446782,-0.000684,0.007725,2474330.0,0.0,4.0,2.024082e+11,36000.0,36000.0,0.006626,0.002558,0.119491,-0.023372,17.9694,10.8900,9.43221,17.96,17.80,18.10,0.289831,0.547945,4.44402,0.006495,0.006626,0.006626,11.0214,1.02016,3.0,7.0,0.0,800000011.0,0.0,54.66370,16599.0,0.029842,0.914796,22.0,421.0,2.0,7.0,1.0,2.0,0.156042,0.256552,0.075366,0.135091,-0.003119,0.504048,0.399707,0.720652,2.73252,0.074618,1.0,2.0,0.0,800000011.0,0.0,7.22268,4637.0,56.0,4.0,0.203615,-5.091270e-14,0.009012,11.8129,12.9922,1.17926,0.007785,0.013951,-0.218836,0.216103,0.270052,-0.017194,2.30402,3.0,5.0,0.0,800000011.0,80000.0,80000.0,80.0,81.0,0.0,7.67300,5870.0,12.5,12.7,12.7,36000.0,0.003307,4.534160e-15,0.256552,1.421090,249.7910,74.5736,0.001305,-0.050907,0.050263,0.079303,-0.151094,4.06894,0.005093,-0.001636,-0.009242,0.000802,-0.001576,-0.001545,-0.001472,-0.001341,-0.001139,-0.000873,-0.000577,-0.000298,-0.000065,0.000078,0.0,0.0,0.0,0.0,800000011.0,0.0,8.56235,4637.0,38.0,3.0,0.0,0.0,0.097197,0.093010,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,0.0,0.005392,2363.68,2335.95,1.5,1.5,1.5,1.2,1.8,2.35404,2.31723,2.42419,0.051332,0.203086,1.58076,0.000077,0.0,0.0,0.0,0.0,800000011.0,1.45,6.75808,18262.0,33.0,0.507556,2.33600,0.338731,47.4394,0.95,3.0,36000.0,36000.0,-26.38320,-0.011653,11.533600,0.107261,2.444880e-11,3.545280e-12,-22.026500,-0.010329,-22.026500,-0.010329,-22.026500,-0.010329,1.19779,1.12821,0.002304,0.008599,1.110390,0.96930,70.0,5655.0,4.0,9.0,1.0,2.0,-0.001145,-0.000131,4.445,4.445,0.433214,0.433214,36000.0,0.0,0.000782,342.752,338.732,1.4,1.4,1.4,1.0,1.8,0.342189,0.340088,0.344678,0.003767,1.217380,5.92224,0.0,0.0,0.0,0.0,800000111.0,1.35,6.41582,18265.0,0.1,0.1,-3.730510,-0.012993,28.0,28.0,-0.000551,-2.584480e-07
2024-08-22 01:45:00,0.024706,1.16689,1181.00,1012.09,0.0,1.0,12.55270,0.0,47.4806,8.91186,547.0,0.5,20.0,30.0,2.03,113.0,-16.0,2.0,-2.5,100.0,9.5,13.2492,-16.0,2.0,-2.5,100.0,9.5,13.2492,36000.0,35988.0,0.0,20.3782,512.958,506.673,1.20,1.30,1.3,1.2,1.4,511.588,506.852,517.399,8.37740,0.507629,4.92329,-0.199634,6.0,0.0,0.0,12.0,0.0,801000000.0,1.25,32.16500,61.0,26.0,0.0,8191.0,100.05,493.388,20.4039,95504.6,1.97145,0.000221,235.062,235.083,94.3453,1.15787,0.025015,0.0,0.0,0.34,36000.0,-0.000577,0.000609,-0.000442,-0.000442,-0.000442,1.30524,0.000996,1.0,36000.0,35988.0,6.399870,-0.008908,1.585380,0.009404,-3.636370e-11,-8.875450e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.517460,-0.006825,5.517460,-0.006825,5.517460,-0.006825,1.15993,1.30524,0.018288,0.000996,1.197390,0.817492,9.0,36.0,1.0,3.0,0.0,1.0,0.0,360.0,35988.0,36000.0,-4.98663,1.163420,0.0,497.380,12.5215,12.3666,3.90,3.9,1.4,1.25,4.0,12.4040,12.375,12.443,0.041982,-0.342920,2.26577,-4.71404,-4.71404,-4.676990,1.06620,0.0,0.0,0.0,0.0,801000011.0,3.85,2.92740,3969.0,0.059305,1.389220,7.0,1.0,0.0,11.0,1.27,1.27,9999.0,9999.0,35988.0,-0.397256,0.419351,-0.304354,-0.304354,-0.304354,1.30524,0.000996,1.0,3.417960,3.446220,0.024864,0.024864,1.0,9.0,6.0,95.5270,94.9717,91.9867,316.5150,-0.042765,0.08,0.02,0.1,0.1,0.0,36000.0,-0.226424,0.015412,0.000022,0.166366,0.000346,0.007730,2474730.0,0.0,4.0,2.024082e+11,36000.0,36000.0,-0.004015,0.001852,0.074181,-0.071984,17.6770,10.7200,9.43686,17.70,17.58,17.80,0.220169,0.274345,9.89008,-0.003889,-0.004015,-0.004015,10.8689,1.03251,15.0,23.0,0.0,800001111.0,0.0,173.22600,14722.0,0.001128,1.829450,24.0,90.0,2.0,5.0,1.0,2.0,0.414759,0.571641,0.058658,0.592317,0.339239,0.785525,0.276100,-0.271783,2.45593,0.057727,2.0,2.0,0.0,800000111.0,0.0,8.62409,1967.0,35.0,3.0,-0.393381,-1.261010e-13,0.009020,11.8166,12.8460,1.02940,0.007790,-0.030265,-0.191911,0.169596,0.258090,0.400223,2.58091,7.0,10.0,0.0,800000001.0,81000.0,81000.0,80.0,81.0,0.0,6.61147,3306.0,12.5,12.7,12.7,36000.0,-0.000427,-1.784440e-15,0.571641,1.326420,332.6240,32.7774,0.000369,-0.039793,0.040494,0.074303,0.036146,5.47008,-0.002352,-0.003992,0.138022,-0.000171,-0.003884,-0.003844,-0.003753,-0.003609,-0.003407,-0.003139,-0.002840,-0.002485,-0.002006,-0.001487,3.0,0.0,8.0,0.0,800000111.0,0.0,10.41040,2150.0,27.0,2.0,0.0,0.0,0.494448,0.490393,-13.0,-4.5,-3.0,600.0,10.0,10.0,-13.0,-4.5,-3.0,600.0,10.0,10.0,36000.0,0.0,0.005279,2314.40,2287.27,1.5,1.5,1.5,1.2,1.8,2.32188,2.29739,2.33233,0.024348,-0.778327,2.65709,0.000016,0.0,0.0,0.0,0.0,800000011.0,1.45,8.89159,18233.0,33.0,0.506778,2.28727,0.337019,47.4380,0.95,3.0,36000.0,36000.0,9.28833,1.476980,4.334050,0.457078,-1.419690e-11,-2.091840e-12,6.439770,1.164720,6.439770,1.164720,6.439770,1.164720,1.44234,1.26810,0.000763,0.004559,1.384320,1.22007,13.0,27.0,1.0,2.0,0.0,0.0,-0.000976,-0.000064,4.445,4.445,0.433287,0.433287,36000.0,0.0,0.000778,341.016,337.018,1.4,1.4,1.4,1.0,1.8,0.340519,0.339047,0.342420,0.002718,1.030340,4.28390,0.0,0.0,0.0,0.0,800000011.0,1.35,6.06567,18241.0,0.1,0.1,-2.189390,-0.077053,28.0,28.0,0.000161,2.913610e-05

# Sort column order

In [5]:
df = df.reindex(sorted(df.columns), axis=1)  # Sort column order
df

,AIR_CP,AIR_DENSITY,AIR_MV,AIR_RHO_CP,AOA_METHOD,AXES_ROTATION_METHOD,BADM_HEIGHTC,BADM_INSTPAIR_EASTWARD_SEP_GA_CH4,BADM_INSTPAIR_EASTWARD_SEP_GA_CO2,BADM_INSTPAIR_EASTWARD_SEP_GA_H2O,BADM_INSTPAIR_EASTWARD_SEP_GA_N2O,BADM_INSTPAIR_HEIGHT_SEP_GA_CH4,BADM_INSTPAIR_HEIGHT_SEP_GA_CO2,BADM_INSTPAIR_HEIGHT_SEP_GA_H2O,BADM_INSTPAIR_HEIGHT_SEP_GA_N2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_CH4,BADM_INSTPAIR_NORTHWARD_SEP_GA_CO2,BADM_INSTPAIR_NORTHWARD_SEP_GA_H2O,BADM_INSTPAIR_NORTHWARD_SEP_GA_N2O,BADM_INST_AVERAGING_INT,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CH4,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_CO2,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_H2O,BADM_INST_GA_CP_TUBE_FLOW_RATE_GA_N2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CH4,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_CO2,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_H2O,BADM_INST_GA_CP_TUBE_IN_DIAM_GA_N2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_CH4,BADM_INST_GA_CP_TUBE_LENGTH_GA_CO2,BADM_INST_GA_CP_TUBE_LENGTH_GA_H2O,BADM_INST_GA_CP_TUBE_LENGTH_GA_N2O,BADM_INST_HEIGHT_SA,BADM_INST_SAMPLING_INT,BADM_LOCATION_ELEV,BADM_LOCATION_LAT,BADM_LOCATION_LONG,BADM_SA_OFFSET_NORTH,BOWEN,BURBA_METHOD,CH4,CH4_ABSLIM_NREX,CH4_DIAG_NREX,CH4_KID,CH4_LGD,CH4_MEAS_KUR,CH4_MEAS_MEDIAN,CH4_MEAS_N2O_MEAS_COV,CH4_MEAS_P25,CH4_MEAS_P75,CH4_MEAS_SIGMA,CH4_MEAS_SKW,CH4_MEAS_TYPE,CH4_MIXING_RATIO,CH4_MOLAR_DENSITY,CH4_NR,CH4_NUM_SPIKES,CH4_SPIKE_NREX,CH4_TLAG_ACTUAL,CH4_TLAG_MAX,CH4_TLAG_MIN,CH4_TLAG_NOMINAL,CH4_TLAG_USED,CH4_VM97_TEST,CH4_ZCD,CO2,CO2_ABSLIM_NREX,CO2_DIAG_NREX,CO2_KID,CO2_LGD,CO2_MEAS_H2O_MEAS_COV,CO2_MEAS_KUR,CO2_MEAS_MEDIAN,CO2_MEAS_P25,CO2_MEAS_P75,CO2_MEAS_SIGMA,CO2_MEAS_SKW,CO2_MEAS_TYPE,CO2_MIXING_RATIO,CO2_MOLAR_DENSITY,CO2_NR,CO2_NUM_SPIKES,CO2_SPIKE_NREX,CO2_TLAG_ACTUAL,CO2_TLAG_MAX,CO2_TLAG_MIN,CO2_TLAG_NOMINAL,CO2_TLAG_USED,CO2_VM97_TEST,CO2_ZCD,CUSTOM_AIR_P_MEAN,CUSTOM_CH4_MEAN,CUSTOM_CO2_MEAN,CUSTOM_COOLER_V_MEAN,CUSTOM_DATA_SIZE_IRGA72_MEAN,CUSTOM_DATA_SIZE_LGR_MEAN,CUSTOM_FILTER_NR,CUSTOM_FILTER_NREX,CUSTOM_FIT_FLAG_MEAN,CUSTOM_FLOWRATE_MEAN,CUSTOM_GA_DIAG_CODE_IRGA72_MEAN,CUSTOM_H2O_MEAN,CUSTOM_MIRROR_RINGDOWNTIME_MEAN,CUSTOM_N2O_MEAN,CUSTOM_SIGNAL_STRENGTH_IRGA72_MEAN,CUSTOM_STATUS_CODE_IRGA72_MEAN,CUSTOM_STATUS_CODE_LGR_MEAN,CUSTOM_T_UNKNOWN_MEAN,DENTRENDING_TIME_CONSTANT,DETRENDING_METHOD,DISPLACEMENT_HEIGHT,DOY_END,DOY_START,DRYAIR_DENSITY,DRYAIR_MV,DRYAIR_PARTIAL_PRESSURE,ET,ET_CORRDIFF,ET_RANDUNC_HF,ET_SCF,ET_SSITC_TEST,ET_STAGE1,ET_STAGE2,ET_UNCORR,EXPECT_NR,FC,FCH4,FCH4_CORRDIFF,FCH4_NR,FCH4_NSR,FCH4_RANDUNC_HF,FCH4_SCF,FCH4_SS,FCH4_SSITC_TEST,FCH4_SS_TEST,FCH4_STAGE1,FCH4_STAGE2,FCH4_UNCORR,FCH4_VADV,FC_CORRDIFF,FC_NR,FC_NSR,FC_RANDUNC_HF,FC_SCF,FC_SS,FC_SSITC_TEST,FC_SS_TEST,FC_STAGE1,FC_STAGE2,FC_UNCORR,FC_VADV,FETCH_10,FETCH_30,FETCH_50,FETCH_70,FETCH_80,FETCH_90,FETCH_MAX,FETCH_OFFSET,FH2O,FH2O_CORRDIFF,FH2O_NSR,FH2O_RANDUNC_HF,FH2O_SCF,FH2O_SS,FH2O_SSITC_TEST,FH2O_SS_TEST,FH2O_STAGE1,FH2O_STAGE2,FH2O_UNCORR,FH2O_VADV,FILE_NR,FILE_TIME_DURATION,FN2O,FN2O_CORRDIFF,FN2O_NR,FN2O_NSR,FN2O_RANDUNC_HF,FN2O_SCF,FN2O_SS,FN2O_SSITC_TEST,FN2O_SS_TEST,FN2O_STAGE1,FN2O_STAGE2,FN2O_UNCORR,FN2O_VADV,FOOTPRINT_MODEL,H,H2O,H2O_ABSLIM_NREX,H2O_DIAG_NREX,H2O_KID,H2O_LGD,H2O_MEAS_CH4_MEAS_COV,H2O_MEAS_KUR,H2O_MEAS_MEDIAN,H2O_MEAS_N2O_MEAS_COV,H2O_MEAS_P25,H2O_MEAS_P75,H2O_MEAS_SIGMA,H2O_MEAS_SKW,H2O_MEAS_TYPE,H2O_MIXING_RATIO,H2O_MOLAR_DENSITY,H2O_NR,H2O_NUM_SPIKES,H2O_SPIKE_NREX,H2O_TLAG_ACTUAL,H2O_TLAG_MAX,H2O_TLAG_MIN,H2O_TLAG_NOMINAL,H2O_TLAG_USED,H2O_VM97_TEST,H2O_ZCD,HPATH_GA_CH4,HPATH_GA_CO2,HPATH_GA_H2O,HPATH_GA_N2O,HPATH_SA,H_CORRDIFF,H_NR,H_NSR,H_RANDUNC_HF,H_SCF,H_SS,H_SSITC_TEST,H_SS_TEST,H_STAGE1,H_STAGE2,H_UNCORR,INST_LI7200_AGC_OR_RSSI,INST_LI7500_AGC_OR_RSSI,LE,LE_CORRDIFF,LE_NR,LE_RANDUNC_HF,LE_SCF,LE_SSITC_TEST,LE_STAGE1,LE_STAGE2,LE_UNCORR,MO_LENGTH,MO_LENGTH_UNCORR,MV_AIR_CELL_CH4,MV_AIR_CELL_CO2,MV_AIR_CELL_H2O,MV_AIR_CELL_N2O,N2O,N2O_ABSLIM_NREX,N2O_DIAG_NREX,N2O_KID,N2O_LGD,N2O_MEAS_KUR,N2O_MEAS_MEDIAN,N2O_MEAS_P25,N2O_MEAS_P75,N2O_MEAS_SIGMA,N2O_MEAS_SKW,N2O_MEAS_TYPE,N2O_MIXING_RATIO,N2O_MOLAR_DENSITY,N2O_NR,N2O_NUM_SPIKES,N2O_SPIKE_NREX,N2O_TLAG_ACTUAL,N2O_TLAG_MAX,N2O_TLAG_MIN,N2O_TLAG_NOMINAL,N2O_TLAG_USED,N2O_VM97_TEST,N2O_ZCD,NIGHT,NUM_BIOMET_VARS,NUM_CUSTOM_VARS,PA_CELL,PA_EP,RESPONSE_TIME_GA_CH4,RESPONSE_TIME_GA_CO2,RESPONSE_TIME_GA_H2O,RESPONSE_TIME_GA_N2O,RESPONSE_TIME_SA,RH_EP,ROT_PITCH,ROT_YAW,ROUGHNESS_LENGTH,SCH4_SINGLE,SC_SINGLE,SET_SINGLE,SH2O_SINGLE,SH_SINGLE,SLE_SINGLE,SN2O_SINGLE,SONIC_DIAG_NREX,SONIC_NR,SPECIFIC_HEAT_EVAP,SPECIFIC_HUMIDITY,SPECTRAL_CORRECTION_METHOD,SW_IN_POT,TAU,TAU_CORRDIFF,TAU_NR,TAU_NSR,TAU_RANDUNC_HF,TAU_SCF,TAU_SS,TAU_SSITC_TEST,TAU_SS_TEST,TAU_STAGE1,TAU_STAGE2,TAU_UNCORR,TA_EP,TDEW,TIMELAG_DETECTION_METHOD,TIMESTAMP_START,TKE,TSTAR,T_CELL,T_SONIC,T_SONIC_ABSLIM_NREX,T_SONIC_ITC,T_SONIC_ITC_TEST,T_SONIC_KID,T_SONIC_KUR,T_SONIC_LGD,T_SONIC_MEDIAN,T_SONIC_NR,T_SONIC_NUM_SPIKES,T_SONIC_P25,T_SONIC_P75,T_SONIC_SIGMA,T_SONIC_SKW,T_SONIC_SPIKE_NREX,T_SONIC_VM97_TEST,T_SONIC_ZCD,U,USTAR,USTAR_UNCORR,U_ABSLIM_NREX,U_ITC,U_ITC_TEST,U_KID,U_KUR,U_LGD,U_MEDIAN,U_NUM_SPIKES,U_P25,U_P75,U_SIGMA,U_SKW,U_SPIKE_NREX,U_UNROT,U_VM97_TEST,U_ZCD,V,VAPOR_DENSITY,VAPOR_DRYAIR_RATIO,VAPOR_PARTIAL_PRESSURE,VAPOR_PARTIAL_PRESSURE_SAT,VM97_AOA_HF,VM97_NSHW_HF,VM97_TLAG_HF,VM97_TLAG_SF,VPATH_GA_CH4,VPATH_GA_CO2,VPATH_GA_H2O,VPATH_GA_N2O,VPATH_SA,VPD_EP,V_ABSLIM_NREX,V_KID,V_KUR,V_LGD,V_MEDIAN,V_NUM_SPIKES,V_P25,V_P75,V_SIGMA,V_SKW,V_SPIKE_NREX,V_UNROT,V_VM97_TEST,V_ZCD,W,WBOOST_APPLIED,WD,WD_FILTER_NR,WD_FILTER_NREX,WD_SIGMA,WPL_APPLIED,WS,WS_MAX,W_ABSLIM_NREX,W_CH4_MEAS_COV,W_CO2_MEAS_COV,W_H2O_MEAS_COV,W_ITC,W_ITC_TEST,W_KID,W_KUR,W_LGD,W_MEDIAN,W_N2O_MEAS_COV,W_NUM_SPIKES,W_P25,W_P75,W_SIGMA,W_SKW,W_SPIKE_NREX,W_T_SONIC_COV,W_T_SONIC_COV_IBROM,W_T_SONIC_COV_IBROM_N0004,W_T_SONIC_COV_IBROM_N0008,W_T_SONIC_COV_IBROM_N0016,W_T_SONIC_COV_IBROM_N0032,W_T_SONIC_COV_IBROM_N0065,W_T_SONIC_COV_IBROM_N0133,W_T_SONIC_COV_IBROM_N0277,W_T_SONIC_COV_IBROM_N0614,W_T_SONIC_COV_IBROM_N1626,W_UNROT,W_U_COV,W_VM97_TEST,W_ZCD,ZL,ZL_UNCORR
TIMESTAMP_MIDDLE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-08-22 00:15:00,1012.16,1.16533,0.024738,1179.50,0.0,1.0,0.5,-4.5,2.0,2.0,-4.5,-3.0,-2.5,-2.5,-3.0,-13.0,-16.0,-16.0,-13.0,30.0,10.0,13.2670,13.2670,10.0,10.0,9.5,9.5,10.0,600.0,100.0,100.0,600.0,2.03,20.0,547.0,47.4806,8.91186,113.0,5.43736,0.0,2329.47,0.0,0.0,7.64521,1.45,4.87225,2.36592,0.000029,2.34596,2.37736,0.029063,-1.426830,0.0,2357.52,0.005379,36000.0,0.0,0.0,1.5,1.8,1.2,1.5,1.5,800000011.0,18261.0,504.612,0.0,0.0,29.65330,1.20,-0.044624,3.11027,508.578,503.942,516.814,13.20010,0.482800,0.0,510.948,20.2703,35988.0,0.0,0.0,1.25,1.4,1.2,1.3,1.25,801000000.0,96.0,95560.2,2.32939,20.2993,1.97733,26.0,33.0,36000.0,0.0,3.0,0.000221,8191.0,498.813,0.95,0.338817,100.05,0.0,0.507556,47.4423,0.0,0.0,0.34,235.021,235.000,1.15624,0.025051,94.3978,-0.000241,0.039353,0.000326,2.08845,2.0,-0.000115,-0.000115,-0.000115,36000.0,-5.362070,-5.38187,0.007094,36000.0,1.022570,3.101760,1.21160,65.0,1.0,4.0,-4.441950,-4.441950,-4.441950,-8.132760e-12,0.137639,35988.0,1.861140,1.468070,2.06604,102.0,2.0,6.0,-2.595330,-2.595330,-2.595330,-3.064910e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003715,0.039353,1.054360,0.005038,2.08845,279.0,2.0,7.0,-0.001779,-0.001779,-0.001779,-7.573500e-13,36000.0,360.0,-0.262678,0.154014,36000.0,2.13904,0.461859,1.19499,130.0,2.0,6.0,-0.219816,-0.219816,-0.219816,-1.182910e-12,0.0,-0.90021,12.4692,0.0,0.0,2.96367,1.35,-0.000269,2.01458,12.5540,-0.000053,12.519,12.588,0.042430,0.094386,0.0,12.6266,500.886,35988.0,0.0,0.0,4.00,4.0,1.25,1.4,1.4,801000111.0,3915.0,4.445,1.27,1.27,4.445,11.0,0.256603,36000.0,1.550550,0.535394,1.46363,35.0,1.0,3.0,-0.62235,-0.615054,-0.62235,9999.0,9999.0,-0.165560,0.039353,35988.0,0.224537,2.08845,2.0,-0.079274,-0.079274,-0.079274,0.210249,0.220852,0.433087,0.024894,0.024894,0.433087,338.820,0.0,0.0,5.90357,1.35,4.22425,0.341617,0.339825,0.344971,0.004411,1.217000,0.0,342.901,0.000782,36000.0,0.0,0.0,1.4,1.8,1.0,1.4,1.4,800000111.0,18266.0,1.0,6.0,9.0,95.0228,95.5900,0.1,0.1,0.1,0.1,0.02,89.4400,0.187709,86.1362,0.08,4.077140,1.007300,-0.000111,-0.001718,-0.607464,-0.076551,0.191593,0.0,36000.0,2473410.0,0.007794,4.0,0.0,0.000200,0.047729,36000.0,0.781083,0.000739,1.23773,128.0,2.0,6.0,0.000200,0.000200,0.000161,11.2767,9.56948,2.0,2.024082e+11,0.033197,-0.058330,11.3720,18.2941,0.0,422.0,7.0,25.41780,4.50305,0.0,18.30,36000.0,3.0,18.18,18.38,0.197375,0.570364,7.0,800000011.0,23953.0,0.057826,0.013084,0.011761,0.0,289.0,7.0,14.34030,2.58896,0.0,0.008752,5.0,-0.087067,0.207973,0.194019,0.565885,9.0,0.003897,800000011.0,13183.0,-5.534510e-14,0.009083,0.007856,11.9225,13.3301,80.0,81.0,80100.0,80100.0,28.0,12.7,12.7,28.0,12.5,1.40766,0.0,11.30220,4.42583,0.0,0.006228,0.0,-0.074405,0.093853,0.164150,-0.503280,0.0,0.057694,800000011.0,14008.0,-1.512020e-15,0.0,206.8970,36000.0,0.0,95.8380,0.0,0.057826,0.852936,0.0,-0.000111,-0.065015,-0.000045,70.0,4.0,11.05330,4.53250,0.0,0.000100,-5.506530e-06,0.0,-0.020454,0.020427,0.042482,-0.016165,0.0,-0.000528,-0.000329,-0.000164,-0.000141,-0.000114,-0.000134,-0.000190,-0.000245,-0.000286,-0.000312,-0.000325,0.000189,0.000093,801000011.0,13215.0,8.038090,7.652170
2024-08-22 00:45:00,1012.11,1.16619,0.024721,1180.31,0.0,1.0,0.5,-4.5,2.0,2.0,-4.5,-3.0,-2.5,-2.5,-3.0,-13.0,-16.0,-16.0,-13.0,30.0,10.0,13.2624,13.2624,10.0,10.0,9.5,9.5,10.0,600.0,100.0,100.0,600.0,2.03,20.0,547.0,47.4806,8.91186,113.0,-1.33447,0.0,2418.92,0.0,0.0,12.19690,1.45,2.59807,2.44274,-0.000125,2.41129,2.48162,0.052564,0.261365,0.0,2447.96,0.005584,35976.0,0.0,0.0,1.5,1.8,1.2,1.5,1.5,800000011.0,18266.0,512.896,0.0,0.0,38.34520,1.25,-0.133184,1.68523,517.297,502.074,535.721,17.97880,0.154933,0.0,519.320,20.6208,35964.0,1.0,2.0,1.30,1.4,1.2,1.3,1.30,801000001.0,68.0,95552.7,2.41886,20.6465,1.97432,26.0,33.0,36000.0,0.0,3.0,0.000221,8191.0,497.928,0.95,0.339024,100.05,0.0,0.507978,47.4354,0.0,0.0,0.34,235.042,235.021,1.15717,0.025031,94.3960,0.002663,0.064482,0.000840,1.09653,1.0,0.002429,0.002429,0.002429,36000.0,1.344980,21.14000,0.020380,35976.0,1.675730,10.141500,1.16300,55.0,1.0,4.0,18.177100,18.177100,18.177100,2.428350e-11,0.013650,35964.0,0.450948,3.661990,1.06796,150.0,2.0,6.0,1.259390,1.259390,1.259390,8.968300e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.041102,0.064482,1.089220,0.012962,1.09653,48.0,1.0,3.0,0.037484,0.037484,0.037484,2.163690e-12,36000.0,360.0,0.356024,0.017867,35976.0,1.12861,0.779504,1.12603,77.0,1.0,5.0,0.316176,0.316176,0.316176,3.403420e-12,0.0,-2.44523,12.3742,0.0,0.0,2.95668,1.35,0.001445,2.52321,12.5370,-0.000100,12.482,12.570,0.067429,-0.318367,0.0,12.5292,497.497,35964.0,0.0,0.0,1.25,4.0,1.25,1.4,1.4,801000011.0,4019.0,4.445,1.27,1.27,4.445,11.0,0.046780,35976.0,1.734820,1.408250,1.04023,38.0,1.0,3.0,-2.25805,-2.350670,-2.25805,9999.0,9999.0,1.832360,0.064482,35964.0,0.577841,1.09653,1.0,1.671050,1.671050,1.671050,13.079700,13.619900,0.433227,0.024873,0.024873,0.433227,339.021,0.0,0.0,5.80783,1.35,3.66200,0.342644,0.339738,0.345821,0.004130,0.736501,0.0,343.090,0.000783,35976.0,0.0,0.0,1.4,1.8,1.0,1.4,1.4,800000111.0,18276.0,1.0,6.0,9.0,95.0185,95.5790,0.1,0.1,0.1,0.1,0.02,90.1333,-0.647087,325.6390,0.08,4.020860,0.373248,-0.000277,-0.004281,-0.310596,-0.190833,0.009007,0.0,35976.0,2473960.0,0.007735,4.0,0.0,-0.006103,0.004837,35976.0,0.660857,0.002613,1.02645,44.0,1.0,3.0,-0.006103,-0.006103,-0.005946,11.0433,9.45399,2.0,2.024082e+11,0.168278,-0.028638,11.1148,18.0501,0.0,327.0,7.0,25.93850,3.86893,0.0,18.10,35976.0,2.0,17.89,18.23,0.269874,-0.767554,3.0,800000001.0,17185.0,0.136575,0.072340,0.071402,0.0,83.0,5.0,6.37583,1.92400,0.0,0.308109,1.0,-0.351551,0.485051,0.451541,-0.470765,2.0,0.112735,800000011.0,4874.0,1.168990e-14,0.009020,0.007795,11.8303,13.1253,80.0,81.0,80000.0,80000.0,28.0,12.7,12.7,28.0,12.5,1.29503,0.0,6.54785,2.27362,0.0,-0.045800,0.0,-0.272969,0.212019,0.357697,0.427838,0.0,-0.077080,800000111.0,6289.0,4.349150e-15,0.0,335.9810,35976.0,0.0,81.7847,0.0,0.136575,1.274790,0.0,0.000455,0.031523,0.000938,44.0,3.0,8.77230,3.55408,0.0,0.003576,7.914060e-06,0.0,-0.043812,0.044498,0.068698,-0.147876,0.0,-0.001913,-0.001549,-0.000315,-0.000531,-0.000753,-0.000960,-0.001150,-0.001305,-0.001417,-0.001487,-0.001530,-0.001542,-0.004007,800000011.0,4874.0,0.129208,0.124083
2024-08-22 01:15:00,1012.10,1.16655,0.024713,1180.66,0.0,1.0,0.5,-4.5,2.0,2.0,-4.5,-3.0,-2.5,-2.5,-3.0,-13.0,-16.0,-16.0,-13.0,30.0,10.0,13.2808,13.2808,10.0,10.0,9.5,9.5,10.0,600.0,100.0,100.0,600.0,2.03,20.0,547.0,47.4806,8.91186,113.0,-1.16190,0.0,2335.95,0.0,0.0,6.75808,1.45,1.58076,2.35404,0.000077,2.31723,2.42419,0.051332,0.203086,0.0,2363.68,0.005392,36000.0,0.0,0.0,1.5,1.8,1.2,1.5,1.5,800000011.0,18262.0,502.983,0.0,0.0,70.27110,1.25,-0.199303,3.27991,508.978,500.990,517.227,10.85680,0.115552,0.0,509.222,20.2247,35988.0,5.0,9.0,1.20,1.4,1.2,1.3,1.30,801000000.0,60.0,95532.5,2.33600,20.2501,1.97320,26.0,33.0,36000.0,0.0,3.0,0.000221,8191.0,493.248,0.95,0.338731,100.05,0.0,0.507556,47.4394,0.0,0.0,0.34,235.062,235.042,1.15754,0.025023,94.3750,0.002601,0.000903,0.000851,1.25324,1.0,0.002076,0.002076,0.002076,36000.0,-0.439665,-26.38320,0.002304,36000.0,1.110390,11.533600,1.19779,70.0,1.0,4.0,-22.026500,-22.026500,-22.026500,2.444880e-11,0.020090,35988.0,1.042770,0.965964,1.19041,568.0,2.0,8.0,-0.369339,-0.369339,-0.369339,9.170200e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.040143,0.000903,1.307430,0.013127,1.25324,16.0,1.0,2.0,0.032032,0.032032,0.032032,2.253240e-12,36000.0,360.0,-0.011653,0.008599,36000.0,0.96930,0.107261,1.12821,5655.0,2.0,9.0,-0.010329,-0.010329,-0.010329,3.545280e-12,0.0,-2.07966,12.3590,0.0,0.0,2.91301,1.35,-0.001145,2.04465,12.3940,-0.000131,12.356,12.454,0.058973,0.228152,0.0,12.5136,496.948,35988.0,0.0,0.0,1.25,4.0,1.25,1.4,1.4,801000011.0,4018.0,4.445,1.27,1.27,4.445,11.0,0.093602,36000.0,0.894161,1.746000,1.03439,16.0,1.0,2.0,-1.93139,-2.010520,-1.93139,9999.0,9999.0,1.789880,0.000903,35988.0,0.585304,1.25324,1.0,1.428210,1.428210,1.428210,17.387300,18.170100,0.433214,0.024870,0.024870,0.433214,338.732,0.0,0.0,6.41582,1.35,5.92224,0.342189,0.340088,0.344678,0.003767,1.217380,0.0,342.752,0.000782,36000.0,0.0,0.0,1.4,1.8,1.0,1.4,1.4,800000111.0,18265.0,1.0,6.0,9.0,94.9990,95.5563,0.1,0.1,0.1,0.1,0.02,90.9233,0.738498,52.5350,0.08,-3.730510,-0.446782,-0.000044,-0.000684,-0.204166,-0.030514,-0.012993,0.0,36000.0,2474330.0,0.007725,4.0,0.0,0.006626,0.029842,36000.0,0.914796,0.002558,1.02016,22.0,1.0,2.0,0.006626,0.006626,0.006495,10.8900,9.43221,2.0,2.024082e+11,0.119491,-0.023372,11.0214,17.9694,0.0,421.0,7.0,54.66370,4.44402,0.0,17.96,36000.0,3.0,17.80,18.10,0.289831,0.547945,7.0,800000011.0,16599.0,0.256552,0.075366,0.074618,0.0,56.0,4.0,7.22268,2.73252,0.0,0.135091,1.0,-0.003119,0.504048,0.399707,0.720652,2.0,0.156042,800000011.0,4637.0,-5.091270e-14,0.009012,0.007785,11.8129,12.9922,80.0,81.0,80000.0,80000.0,28.0,12.7,12.7,28.0,12.5,1.17926,0.0,7.67300,2.30402,0.0,0.013951,3.0,-0.218836,0.216103,0.270052,-0.017194,5.0,0.203615,800000011.0,5870.0,4.534160e-15,0.0,249.7910,36000.0,0.0,74.5736,0.0,0.256552,1.421090,0.0,-0.000551,-0.009242,0.000802,38.0,3.0,8.56235,4.06894,0.0,0.001305,-2.584480e-07,0.0,-0.050907,0.050263,0.079303,-0.151094,0.0,-0.001636,-0.001576,0.000078,-0.000065,-0.000298,-0.000577,-0.000873,-0.001139,-0.001341,-0.001472,-0.001545,0.003307,0.005093,800000011.0,4637.0,0.097197,0.093010
2024-08-22 01:45:00,1012.09,1.16689,0.024706,1181.00,0.0,1.0,0.5,-4.5,2.0,2.0,-4.5,-3.0,-2.5,-2.5,-3.0,-13.0,-16.0,-16.0,-13.0,30.0,10.0,13.2492,13.2492,10.0,10.0,9.5,9.5,10.0,600.0,100.0,100.0,600.0,2.03,20.0,547.0,47.4806,8.91186,113.0,12.55270,0.0,2287.27,0.0,0.0,8.89159,1.45,2.65709,2.32188,0.000016,2.29739,2.33233,0.024348,-0.778327,0.0,2314.40,0.005279,36000.0,0.0,0.0,1.5,1.8,1.2,1.5,1.5,800000011.0,18233.0,506.673,0.0,0.0,32.16500,1.25,-0.199634,4.92329,511.588,506.852,517.399,8.37740,0.507629,0.0,512.958,20.3782,35988.0,6.0,12.0,1.20,1.4,1.2,1.3,1.30,801000000.0,61.0,95504.6,2.28727,20.4039,1.97145,26.0,33.0,36000.0,0.0,3.0,0.000221,8191.0,493.388,0.95,0.337019,100.05,0.0,0.506778,47.4380,0.0,0.0,0.34,235.083,235.062,1.15787,0.025015,94.3453,-0.000577,0.000996,0.000609,1.30524,1.0,-0.000442,-0.000442,-0.000442,36000.0,6.399870,9.28833,0.000763,36000.0,1.384320,4.334050,1.44234,13.0,0.0,1.0,6.439770,6.439770,6.439770,-1.419690e-11,0.018288,35988.0,1.197390,1.585380,1.15993,9.0,0.0,1.0,5.517460,5.517460,5.517460,-3.636370e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008908,0.000996,0.817492,0.009404,1.30524,36.0,1.0,3.0,-0.006825,-0.006825,-0.006825,-8.875450e-13,36000.0,360.0,1.476980,0.004559,36000.0,1.22007,0.457078,1.26810,27.0,0.0,2.0,1.164720,1.164720,1.164720,-2.091840e-12,0.0,-4.98663,12.3666,0.0,0.0,2.92740,3.85,-0.000976,2.26577,12.4040,-0.000064,12.375,12.443,0.041982,-0.342920,0.0,12.5215,497.380,35988.0,0.0,0.0,3.90,4.0,1.25,1.4,3.9,801000011.0,3969.0,4.445,1.27,1.27,4.445,11.0,0.059305,36000.0,1.389220,1.163420,1.06620,7.0,0.0,1.0,-4.71404,-4.676990,-4.71404,9999.0,9999.0,-0.397256,0.000996,35988.0,0.419351,1.30524,1.0,-0.304354,-0.304354,-0.304354,3.417960,3.446220,0.433287,0.024864,0.024864,0.433287,337.018,0.0,0.0,6.06567,1.35,4.28390,0.340519,0.339047,0.342420,0.002718,1.030340,0.0,341.016,0.000778,36000.0,0.0,0.0,1.4,1.8,1.0,1.4,1.4,800000011.0,18241.0,1.0,6.0,9.0,94.9717,95.5270,0.1,0.1,0.1,0.1,0.02,91.9867,-0.042765,316.5150,0.08,-2.189390,0.166366,0.000022,0.000346,-0.226424,0.015412,-0.077053,0.0,36000.0,2474730.0,0.007730,4.0,0.0,-0.004015,0.001128,36000.0,1.829450,0.001852,1.03251,24.0,1.0,2.0,-0.004015,-0.004015,-0.003889,10.7200,9.43686,2.0,2.024082e+11,0.074181,-0.071984,10.8689,17.6770,0.0,90.0,5.0,173.22600,9.89008,0.0,17.70,36000.0,15.0,17.58,17.80,0.220169,0.274345,23.0,800001111.0,14722.0,0.571641,0.058658,0.057727,0.0,35.0,3.0,8.62409,2.45593,0.0,0.592317,2.0,0.339239,0.785525,0.276100,-0.271783,2.0,0.414759,800000111.0,1967.0,-1.261010e-13,0.009020,0.007790,11.8166,12.8460,80.0,81.0,81000.0,81000.0,28.0,12.7,12.7,28.0,12.5,1.02940,0.0,6.61147,2.58091,0.0,-0.030265,7.0,-0.191911,0.169596,0.258090,0.400223,10.0,-0.393381,800000001.0,3306.0,-1.784440e-15,0.0,332.6240,36000.0,0.0,32.7774,0.0,0.571641,1.326420,0.0,0.000161,0.138022,-0.000171,27.0,2.0,10.41040,5.47008,0.0,0.000369,2.913610e-05,3.0,-0.039793,0.040494,0.074303,0.036146,8.0,-0.003992,-0.003884,-0.001487,-0.002006,-0.002485,-0.002840,-0.003139,-0.003407,-0.003609,-0.003753,-0.003844,-0.000427,-0.002352,800000111.0,2150.0,0.494448,0.490393

# Save to file

In [6]:
OUTNAME = "33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet"
filepath = save_parquet(filename=OUTNAME, data=df)

Saved file 33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet (0.410 seconds).

# **End of notebook**.

In [7]:
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-10-06 15:22:12