# Imports

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

# Load L3.3 results for NEE, LE and H

In [2]:
nee = load_parquet(filepath=r"41_NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet")
le = load_parquet(filepath=r"42_LE/42.1_FluxProcessingChain_L3.2_LE.parquet")
h = load_parquet(filepath=r"43_H/43.1_FluxProcessingChain_L3.2_H.parquet")
n2o = load_parquet(filepath=r"44_FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet")
ch4 = load_parquet(filepath=r"45_FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet")

Loaded .parquet file 41_NEE/41.1_FluxProcessingChain_L3.2_NEE.parquet (0.122 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 42_LE/42.1_FluxProcessingChain_L3.2_LE.parquet (0.080 seconds).

    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file 43_H/43.1_FluxProcessingChain_L3.2_H.parquet (0.085 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

Loaded .parquet file 44_FN2O/44.1_FluxProcessingChain_L3.2_FN2O.parquet (0.089 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

Loaded .parquet file 45_FCH4/45.1_FluxProcessingChain_L3.2_FCH4.parquet (0.083 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

In [3]:
# Load METEO
SOURCEDIR = r"../10_METEO"
FILENAME = r"13.1_CH-TAN_meteo_gapfilled.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
meteo = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\10_METEO\13.1_CH-TAN_meteo_gapfilled.parquet (0.016 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# Load main data

In [4]:
SOURCEDIR = r"../30_MERGE_DATA"
FILENAME = r"33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet"
FILEPATH = Path(SOURCEDIR) / FILENAME
maindf = load_parquet(filepath=FILEPATH)

Loaded .parquet file ..\30_MERGE_DATA\33.1_CH-TAN_IRGA+LGR_Level-1_eddypro_fluxnet.parquet (0.074 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

## Add results for NEE

In [5]:
newcols = [c for c in nee.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, nee[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ DAYTIME
++ NIGHTTIME
++ FLAG_L2_FC_MISSING_TEST
++ FLAG_L2_FC_SSITC_TEST
++ FLAG_L2_FC_COMPLETENESS_TEST
++ FLAG_L2_FC_SCF_TEST
++ FLAG_L2_FC_SIGNAL_STRENGTH_TEST
++ FLAG_L2_FC_CO2_VM97_SPIKE_HF_TEST
++ FLAG_L2_FC_CO2_VM97_DROPOUT_TEST
++ SUM_L2_FC_HARDFLAGS
++ SUM_L2_FC_SOFTFLAGS
++ SUM_L2_FC_FLAGS
++ FLAG_L2_FC_QCF
++ FC_L2_QCF
++ FC_L2_QCF0
++ SC_SINGLE_gfRMED_L3.1
++ FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED
++ NEE_L3.1
++ NEE_L3.1_QCF
++ NEE_L3.1_QCF0
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST
++ SUM_L3.2_NEE_L3.1_HARDFLAGS
++ SUM_L3.2_NEE_L3.1_SOFTFLAGS
++ SUM_L3.2_NEE_L3.1_FLAGS
++ FLAG_L3.2_NEE_L3.1_QCF
++ NEE_L3.1_L3.2_QCF
++ NEE_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  SC_SINGLE_gfRMED_L3.1  FLAG_SC_SINGLE_gfRMED_L3.1_ISFILLED   NEE_L3.1  NEE_L3.1_QCF  NEE_L3.1_QCF0  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_NEE_L3.1_QCF_OUTLIER_HAMPELDTNT_TEST  SUM_L3.2_NEE_L3.1_HARDFLAGS  SUM_L3.2_NEE_L3.1_SOFTFLAGS  SUM_L3.2_NEE_L3.1_FLAGS  FLAG_L3.2_NEE_L3.1_QCF  NEE_L3.1_L3.2_QCF  NEE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               1.007300                                  0.0  -4.354770           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          1.0                      3.0                     2.0                NaN                 NaN
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.373248                                  0.0   1.718228           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...              -0.446782                                  0.0  -0.886447           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          2.0                          0.0                      2.0                     2.0                NaN                 NaN
2024-08-22 01:45:00  1012.09      1.16689  0.024706     1181.00         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.166366                                  0.0   6.566236      6.566236       6.566236                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0           6.566236            6.566236
2024-08-22 02:15:00  1012.09      1.16615  0.024722     1180.25         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...              -0.584678                                  0.0   3.657172           NaN            NaN                                         0.0                                  False                                         0.0                                             0.0                          0.0                          1.0                      1.0                     2.0                NaN                 NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                    ...                                  ...        ...           ...            ...                                         ...                                    ...                                         ...                                             ...                          ...                          ...                      ...                     ...                ...                 ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.012762                                  0.0  10.578562     10.578562      10.578562                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0          10.578562           10.578562
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.051059                                  0.0   9.416519      9.416519       9.416519                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0           9.416519            9.416519
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...              -0.004990                                  0.0  10.095010     10.095010      10.095010                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0          10.095010           10.095010
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.013002                                  0.0   8.641342      8.641342       8.641342                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0           8.641342            8.641342
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...               0.023613                                  0.0   8.664543      8.664543       8.664543                                         0.0                                  False                                         0.0                                             0.0                          0.0                          0.0                      0.0                     0.0           8.664543            8.664543

[13776 rows x 455 columns]

## Add results for LE

In [6]:
newcols = [c for c in le.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, le[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_LE_MISSING_TEST
++ FLAG_L2_LE_SSITC_TEST
++ FLAG_L2_LE_COMPLETENESS_TEST
++ FLAG_L2_LE_SCF_TEST
++ FLAG_L2_LE_SIGNAL_STRENGTH_TEST
++ FLAG_L2_LE_H2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_LE_H2O_VM97_DROPOUT_TEST
++ SUM_L2_LE_HARDFLAGS
++ SUM_L2_LE_SOFTFLAGS
++ SUM_L2_LE_FLAGS
++ FLAG_L2_LE_QCF
++ LE_L2_QCF
++ LE_L2_QCF0
++ SLE_SINGLE_gfRMED_L3.1
++ FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED
++ LE_L3.1
++ LE_L3.1_QCF
++ LE_L3.1_QCF0
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_LE_L3.1_HARDFLAGS
++ SUM_L3.2_LE_L3.1_SOFTFLAGS
++ SUM_L3.2_LE_L3.1_FLAGS
++ FLAG_L3.2_LE_L3.1_QCF
++ LE_L3.1_L3.2_QCF
++ LE_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  LE_L2_QCF0  SLE_SINGLE_gfRMED_L3.1  FLAG_SLE_SINGLE_gfRMED_L3.1_ISFILLED   LE_L3.1  LE_L3.1_QCF  LE_L3.1_QCF0  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_LE_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_LE_L3.1_HARDFLAGS  SUM_L3.2_LE_L3.1_SOFTFLAGS  SUM_L3.2_LE_L3.1_FLAGS  FLAG_L3.2_LE_L3.1_QCF  LE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.076551                                   0.0 -0.242111          NaN           NaN                                        0.0                                 False                                        0.0                         2.0                         1.0                     3.0                    2.0               NaN                NaN
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.190833                                   0.0  1.641527          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.030514                                   0.0  1.759366          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2024-08-22 01:45:00  1012.09      1.16689  0.024706     1181.00         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN                0.015412                                   0.0 -0.381844          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2024-08-22 02:15:00  1012.09      1.16615  0.024722     1180.25         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.031870                                   0.0  0.316839          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...         ...                     ...                                   ...       ...          ...           ...                                        ...                                   ...                                        ...                         ...                         ...                     ...                    ...               ...                ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -0.191570                                   0.0  9.814630          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...     2.86427                0.281333                                   0.0  3.145603     3.145603      3.145603                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0          3.145603           3.145603
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...     3.72513                0.053195                                   0.0  3.778325     3.778325      3.778325                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0          3.778325           3.778325
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...    -1.05712                0.109881                                   0.0 -0.947239    -0.947239     -0.947239                                        0.0                                 False                                        0.0                         0.0                         0.0                     0.0                    0.0         -0.947239          -0.947239
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...         NaN               -1.944100                                   0.0 -4.271550          NaN           NaN                                        0.0                                 False                                        0.0                         0.0                         1.0                     1.0                    2.0               NaN                NaN

[13776 rows x 482 columns]

## Add results for H

In [7]:
newcols = [c for c in h.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, h[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_H_MISSING_TEST
++ FLAG_L2_H_SSITC_TEST
++ FLAG_L2_H_COMPLETENESS_TEST
++ FLAG_L2_H_SCF_TEST
++ FLAG_L2_H_T_SONIC_VM97_SPIKE_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_H_T_SONIC_VM97_DROPOUT_TEST
++ SUM_L2_H_HARDFLAGS
++ SUM_L2_H_SOFTFLAGS
++ SUM_L2_H_FLAGS
++ FLAG_L2_H_QCF
++ H_L2_QCF
++ H_L2_QCF0
++ SH_SINGLE_gfRMED_L3.1
++ FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED
++ H_L3.1
++ H_L3.1_QCF
++ H_L3.1_QCF0
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST
++ SUM_L3.2_H_L3.1_HARDFLAGS
++ SUM_L3.2_H_L3.1_SOFTFLAGS
++ SUM_L3.2_H_L3.1_FLAGS
++ FLAG_L3.2_H_L3.1_QCF
++ H_L3.1_L3.2_QCF
++ H_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  H_L2_QCF0  SH_SINGLE_gfRMED_L3.1  FLAG_SH_SINGLE_gfRMED_L3.1_ISFILLED     H_L3.1  H_L3.1_QCF  H_L3.1_QCF0  FLAG_L3.2_H_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_H_L3.1_QCF_OUTLIER_HQROLL_TEST  SUM_L3.2_H_L3.1_HARDFLAGS  SUM_L3.2_H_L3.1_SOFTFLAGS  SUM_L3.2_H_L3.1_FLAGS  FLAG_L3.2_H_L3.1_QCF  H_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.607464                                  0.0  -1.507674         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.310596                                  0.0  -2.755826         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN              -0.204166                                  0.0  -2.283826         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
2024-08-22 01:45:00  1012.09      1.16689  0.024706     1181.00         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...   -4.98663              -0.226424                                  0.0  -5.213054   -5.213054    -5.213054                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0        -5.213054         -5.213054
2024-08-22 02:15:00  1012.09      1.16615  0.024722     1180.25         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...        NaN               0.133106                                  0.0  -2.135644         NaN          NaN                                       0.0                                False                                       0.0                        0.0                        1.0                    1.0                   2.0              NaN               NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...        ...                    ...                                  ...        ...         ...          ...                                       ...                                  ...                                       ...                        ...                        ...                    ...                   ...              ...               ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...  -37.67390              -0.121744                                  0.0 -37.795644  -37.795644   -37.795644                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -37.795644        -37.795644
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...  -33.34900              -0.230604                                  0.0 -33.579604  -33.579604   -33.579604                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -33.579604        -33.579604
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...  -39.18460               0.187053                                  0.0 -38.997547  -38.997547   -38.997547                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -38.997547        -38.997547
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...  -39.78420              -0.065275                                  0.0 -39.849475  -39.849475   -39.849475                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -39.849475        -39.849475
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...  -53.15220              -0.361662                                  0.0 -53.513862  -53.513862   -53.513862                                       0.0                                False                                       0.0                        0.0                        0.0                    0.0                   0.0       -53.513862        -53.513862

[13776 rows x 509 columns]

## Add results for N2O

In [8]:
newcols = [c for c in n2o.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, n2o[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FN2O_MISSING_TEST
++ FLAG_L2_FN2O_SSITC_TEST
++ FLAG_L2_FN2O_COMPLETENESS_TEST
++ FLAG_L2_FN2O_SCF_TEST
++ FLAG_L2_FN2O_N2O_VM97_SPIKE_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FN2O_N2O_VM97_DROPOUT_TEST
++ SUM_L2_FN2O_HARDFLAGS
++ SUM_L2_FN2O_SOFTFLAGS
++ SUM_L2_FN2O_FLAGS
++ FLAG_L2_FN2O_QCF
++ FN2O_L2_QCF
++ FN2O_L2_QCF0
++ SN2O_SINGLE_gfRMED_L3.1
++ FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED
++ FN2O_L3.1
++ FN2O_L3.1_QCF
++ FN2O_L3.1_QCF0
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FN2O_L3.1_HARDFLAGS
++ SUM_L3.2_FN2O_L3.1_SOFTFLAGS
++ SUM_L3.2_FN2O_L3.1_FLAGS
++ FLAG_L3.2_FN2O_L3.1_QCF
++ FN2O_L3.1_L3.2_QCF
++ FN2O_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SN2O_SINGLE_gfRMED_L3.1_ISFILLED  FN2O_L3.1  FN2O_L3.1_QCF  FN2O_L3.1_QCF0  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FN2O_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FN2O_L3.1_HARDFLAGS  SUM_L3.2_FN2O_L3.1_SOFTFLAGS  SUM_L3.2_FN2O_L3.1_FLAGS  FLAG_L3.2_FN2O_L3.1_QCF  FN2O_L3.1_L3.2_QCF  FN2O_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.071085            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.365031       0.365031             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            0.365031                  NaN
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.024646            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2024-08-22 01:45:00  1012.09      1.16689  0.024706     1181.00         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   1.399927       1.399927        1.399927                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            1.399927             1.399927
2024-08-22 02:15:00  1012.09      1.16615  0.024722     1180.25         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   1.017312       1.017312             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0            1.017312                  NaN
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.524032       0.524032        0.524032                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.524032             0.524032
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.001803            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.069384      -0.069384       -0.069384                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -0.069384            -0.069384
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.288296      -0.288296       -0.288296                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0           -0.288296            -0.288296
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   0.220511       0.220511        0.220511                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            0.220511             0.220511

[13776 rows x 538 columns]

## Add results for CH4

In [9]:
newcols = [c for c in ch4.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"++ {c}") for c in newcols]
maindf = pd.concat([maindf, ch4[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
++ FLAG_L2_FCH4_MISSING_TEST
++ FLAG_L2_FCH4_SSITC_TEST
++ FLAG_L2_FCH4_COMPLETENESS_TEST
++ FLAG_L2_FCH4_SCF_TEST
++ FLAG_L2_FCH4_CH4_VM97_SPIKE_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_AMPLITUDE_RESOLUTION_HF_TEST
++ FLAG_L2_FCH4_CH4_VM97_DROPOUT_TEST
++ SUM_L2_FCH4_HARDFLAGS
++ SUM_L2_FCH4_SOFTFLAGS
++ SUM_L2_FCH4_FLAGS
++ FLAG_L2_FCH4_QCF
++ FCH4_L2_QCF
++ FCH4_L2_QCF0
++ SCH4_SINGLE_gfRMED_L3.1
++ FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED
++ FCH4_L3.1
++ FCH4_L3.1_QCF
++ FCH4_L3.1_QCF0
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST
++ FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST
++ SUM_L3.2_FCH4_L3.1_HARDFLAGS
++ SUM_L3.2_FCH4_L3.1_SOFTFLAGS
++ SUM_L3.2_FCH4_L3.1_FLAGS
++ FLAG_L3.2_FCH4_L3.1_QCF
++ FCH4_L3.1_L3.2_QCF
++ FCH4_L3.1_L3.2_QCF0

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_SCH4_SINGLE_gfRMED_L3.1_ISFILLED  FCH4_L3.1  FCH4_L3.1_QCF  FCH4_L3.1_QCF0  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ABSLIM_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HQROLL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_HAMPEL_TEST  FLAG_L3.2_FCH4_L3.1_QCF_OUTLIER_ZSCOREROLLING_TEST  SUM_L3.2_FCH4_L3.1_HARDFLAGS  SUM_L3.2_FCH4_L3.1_SOFTFLAGS  SUM_L3.2_FCH4_L3.1_FLAGS  FLAG_L3.2_FCH4_L3.1_QCF  FCH4_L3.1_L3.2_QCF  FCH4_L3.1_L3.2_QCF0
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.304730      -1.304730             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -1.304730                  NaN
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  25.160860      25.160860             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           25.160860                  NaN
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0 -30.113710     -30.113710             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0          -30.113710                  NaN
2024-08-22 01:45:00  1012.09      1.16689  0.024706     1181.00         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   7.098940       7.098940        7.098940                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            7.098940             7.098940
2024-08-22 02:15:00  1012.09      1.16615  0.024722     1180.25         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   3.274850       3.274850        3.274850                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            3.274850             3.274850
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                    ...        ...            ...             ...                                          ...                                     ...                                          ...                                          ...                                                ...                            ...                           ...                       ...                      ...                 ...                  ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   2.489636       2.489636             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           2.0                       2.0                      1.0            2.489636                  NaN
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -0.987718      -0.987718             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -0.987718                  NaN
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0   2.160966       2.160966        2.160966                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           0.0                       0.0                      0.0            2.160966             2.160966
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.904577      -1.904577             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            0.0                           1.0                       1.0                      1.0           -1.904577                  NaN
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                    0.0  -1.679224            NaN             NaN                                          0.0                                   False                                          0.0                                          0.0                                                0.0                            2.0                           0.0                       2.0                      2.0                 NaN                  NaN

[13776 rows x 567 columns]

# Export

## Export all data

In [10]:
filename = "46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4"
save_parquet(data=maindf, filename=filename)

Saved file 46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet (0.977 seconds).

'46.1_FLUXES_L3.2_NEE_LE_H_FN2O_FCH4.parquet'

## Export subset for REddyProc

In [11]:
from diive.core.times.times import insert_timestamp
export_REddyProc = maindf.copy()

In [12]:
newcols = [c for c in meteo.columns if c not in export_REddyProc]
export_REddyProc = pd.concat([export_REddyProc, meteo[newcols]], axis=1)

In [13]:
exportcols = ['NEE_L3.1_L3.2_QCF', 'LE_L3.1_L3.2_QCF', 'H_L3.1_L3.2_QCF',
              'USTAR',
              'sw_in', 'ta', 'vpd']
export_REddyProc = export_REddyProc[exportcols].copy()
locs = (export_REddyProc.index.year >= 2024) & (export_REddyProc.index.year <= 2025)
export_REddyProc = export_REddyProc[locs].copy()
export_REddyProc = insert_timestamp(data=export_REddyProc, convention="end", set_as_index=True)
export_REddyProc

                     NEE_L3.1_L3.2_QCF  LE_L3.1_L3.2_QCF  H_L3.1_L3.2_QCF     USTAR  sw_in         ta       vpd
TIMESTAMP_END
2024-08-22 00:30:00                NaN               NaN              NaN  0.013084    0.0  11.276667  0.141369
2024-08-22 01:00:00                NaN               NaN              NaN  0.072340    0.0  11.043333  0.130055
2024-08-22 01:30:00                NaN               NaN              NaN  0.075366    0.0  10.890000  0.118427
2024-08-22 02:00:00           6.566236               NaN        -5.213054  0.058658    0.0  10.720000  0.103376
2024-08-22 02:30:00                NaN               NaN              NaN  0.035749    0.0  10.820000  0.113850
...                                ...               ...              ...       ...    ...        ...       ...
2025-06-04 22:00:00          10.578562               NaN       -37.795644  0.413091    0.0  15.693333  0.308913
2025-06-04 22:30:00           9.416519          3.145603       -33.579604  0.353844    0.0  15.516667  0.275008
2025-06-04 23:00:00          10.095010          3.778325       -38.997547  0.409273    0.0  15.660000  0.288298
2025-06-04 23:30:00           8.641342         -0.947239       -39.849475  0.330784    0.0  15.610000  0.276955
2025-06-05 00:00:00           8.664543               NaN       -53.513862  0.375659    0.0  15.293103  0.239388

[13776 rows x 7 columns]

In [14]:
filename = "46.2_FluxProcessingChain_L3.2_subset-forREddyProc"
export_REddyProc.to_csv(f"{filename}.csv", index=True)

</br>

---

# **End of notebook**

---

Congratulations, you reached the end of this notebook! Before you go let's store your finish time.

In [15]:
from datetime import datetime
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-10-06 15:25:32