# IMPORTS

In [1]:
from pathlib import Path
import pandas as pd
from diive.core.io.files import save_parquet, load_parquet

In [2]:
# Project settings (dataset period, data paths): see src/config.py
import sys
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "src" / "config.py").is_file())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.config import DATA_DIR, PERIOD_START, PERIOD_END, select_period
print(f"Dataset period: {PERIOD_START} to {PERIOD_END} (CET, UTC+1)")

Dataset period: 2024-08-22 00:00:00 to 2025-06-05 00:00:00 (CET, UTC+1)

# LOAD DATA

In [3]:
maindf = load_parquet(filepath=r"../70_SPLIT_TREATMENTS/71.1_FLUXES_L3.3_NEE_LE_H_FN2O_FCH4_REDDYPROC_PARCELS.parquet")
gf_part = load_parquet(filepath=r"../80_GAP-FILLING/84.1_GF-FLUXES+PARTITIONED.parquet")
meteo = load_parquet(filepath=r"../10_METEO/13.1_CH-TAN_meteo_gapfilled.parquet")
management = load_parquet(filepath=r"../20_MANAGEMENT/21.1_mgmt_full_timestamp.parquet")

Loaded .parquet file ../70_SPLIT_TREATMENTS/71.1_FLUXES_L3.3_NEE_LE_H_FN2O_FCH4_REDDYPROC_PARCELS.parquet (0.153 seconds).

    --> Detected time resolution of <30 * Minutes> / 30min

Loaded .parquet file ../80_GAP-FILLING/84.1_GF-FLUXES+PARTITIONED.parquet (0.361 seconds).

    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../10_METEO/13.1_CH-TAN_meteo_gapfilled.parquet (0.009 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min
Loaded .parquet file ../20_MANAGEMENT/21.1_mgmt_full_timestamp.parquet (0.011 seconds).
    --> Detected time resolution of <30 * Minutes> / 30min

# MERGE

## Gap-filled & partitioned fluxes

In [4]:
newcols = [c for c in gf_part.columns if c not in maindf]
print("NEW VARIABLES FROM FLUX PROCESSING CHAIN:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, gf_part[newcols]], axis=1)
maindf

NEW VARIABLES FROM FLUX PROCESSING CHAIN:
+ NEE_L3.3_CUT_16_QCF_parcelA
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_yhat
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost
+ FLAG_NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_total_unc
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens00
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens01
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens02
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens03
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens04
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens05
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens06
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens07
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens08
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens09
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens10
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens11
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens12
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens13
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens14
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens15
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens16
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens17
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens18
+ NEE_L3.3_CUT_16_QCF_parcelA_gfXGBoost_ens19
+ NEE_L3.3_CUT_16_QCF0_parcelA
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_yhat
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost
+ FLAG_NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_total_unc
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens00
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens01
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens02
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens03
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens04
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens05
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens06
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens07
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens08
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens09
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens10
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens11
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens12
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens13
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens14
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens15
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens16
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens17
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens18
+ NEE_L3.3_CUT_16_QCF0_parcelA_gfXGBoost_ens19
+ NEE_L3.3_CUT_16_QCF_parcelB
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_yhat
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost
+ FLAG_NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_total_unc
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens00
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens01
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens02
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens03
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens04
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens05
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens06
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens07
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens08
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens09
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens10
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens11
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens12
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens13
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens14
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens15
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens16
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens17
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens18
+ NEE_L3.3_CUT_16_QCF_parcelB_gfXGBoost_ens19
+ NEE_L3.3_CUT_16_QCF0_parcelB
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_yhat
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost
+ FLAG_NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_total_unc
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens00
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens01
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens02
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens03
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens04
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens05
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens06
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens07
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens08
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens09
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens10
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens11
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens12
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens13
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens14
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens15
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens16
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens17
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens18
+ NEE_L3.3_CUT_16_QCF0_parcelB_gfXGBoost_ens19
+ NEE_L3.3_CUT_16_QCF_footprint
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_yhat
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost
+ FLAG_NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_total_unc
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens00
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens01
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens02
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens03
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens04
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens05
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens06
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens07
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens08
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens09
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens10
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens11
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens12
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens13
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens14
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens15
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens16
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens17
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens18
+ NEE_L3.3_CUT_16_QCF_footprint_gfXGBoost_ens19
+ NEE_L3.3_CUT_16_QCF0_footprint
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_yhat
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost
+ FLAG_NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_total_unc
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens00
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens01
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens02
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens03
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens04
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens05
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens06
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens07
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens08
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens09
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens10
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens11
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens12
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens13
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens14
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens15
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens16
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens17
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens18
+ NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ens19
+ NEE_L3.3_CUT_50_QCF_parcelA
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_yhat
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost
+ FLAG_NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_total_unc
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens00
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens01
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens02
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens03
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens04
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens05
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens06
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens07
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens08
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens09
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens10
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens11
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens12
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens13
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens14
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens15
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens16
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens17
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens18
+ NEE_L3.3_CUT_50_QCF_parcelA_gfXGBoost_ens19
+ NEE_L3.3_CUT_50_QCF0_parcelA
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_yhat
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost
+ FLAG_NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_total_unc
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens00
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens01
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens02
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens03
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens04
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens05
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens06
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens07
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens08
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens09
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens10
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens11
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens12
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens13
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens14
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens15
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens16
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens17
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens18
+ NEE_L3.3_CUT_50_QCF0_parcelA_gfXGBoost_ens19
+ NEE_L3.3_CUT_50_QCF_parcelB
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_yhat
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost
+ FLAG_NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_total_unc
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens00
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens01
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens02
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens03
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens04
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens05
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens06
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens07
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens08
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens09
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens10
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens11
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens12
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens13
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens14
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens15
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens16
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens17
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens18
+ NEE_L3.3_CUT_50_QCF_parcelB_gfXGBoost_ens19
+ NEE_L3.3_CUT_50_QCF0_parcelB
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_yhat
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost
+ FLAG_NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_total_unc
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens00
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens01
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens02
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens03
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens04
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens05
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens06
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens07
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens08
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens09
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens10
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens11
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens12
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens13
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens14
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens15
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens16
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens17
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens18
+ NEE_L3.3_CUT_50_QCF0_parcelB_gfXGBoost_ens19
+ NEE_L3.3_CUT_50_QCF_footprint
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_yhat
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost
+ FLAG_NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_total_unc
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens00
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens01
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens02
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens03
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens04
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens05
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens06
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens07
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens08
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens09
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens10
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens11
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens12
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens13
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens14
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens15
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens16
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens17
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens18
+ NEE_L3.3_CUT_50_QCF_footprint_gfXGBoost_ens19
+ NEE_L3.3_CUT_50_QCF0_footprint
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_yhat
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost
+ FLAG_NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_total_unc
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens00
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens01
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens02
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens03
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens04
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens05
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens06
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens07
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens08
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens09
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens10
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens11
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens12
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens13
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens14
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens15
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens16
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens17
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens18
+ NEE_L3.3_CUT_50_QCF0_footprint_gfXGBoost_ens19
+ NEE_L3.3_CUT_84_QCF_parcelA
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_yhat
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost
+ FLAG_NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_total_unc
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens00
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens01
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens02
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens03
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens04
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens05
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens06
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens07
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens08
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens09
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens10
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens11
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens12
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens13
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens14
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens15
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens16
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens17
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens18
+ NEE_L3.3_CUT_84_QCF_parcelA_gfXGBoost_ens19
+ NEE_L3.3_CUT_84_QCF0_parcelA
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_yhat
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost
+ FLAG_NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_total_unc
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens00
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens01
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens02
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens03
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens04
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens05
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens06
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens07
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens08
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens09
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens10
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens11
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens12
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens13
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens14
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens15
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens16
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens17
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens18
+ NEE_L3.3_CUT_84_QCF0_parcelA_gfXGBoost_ens19
+ NEE_L3.3_CUT_84_QCF_parcelB
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_yhat
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost
+ FLAG_NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ISFILLED
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_sigmaGF
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_sigmaResid
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_sigmaEns
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_total_unc
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_sigmaObs
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens00
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens01
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens02
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens03
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens04
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens05
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens06
+ NEE_L3.3_CUT_84_QCF_parcelB_gfXGBoost_ens07

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens05  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens06  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens07  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens08  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens09  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens10  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens11  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens12  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens13  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens14  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens15  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens16  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens17  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens18  FCH4_L3.3_CUT_84_QCF0_footprint_gfXGBoost_ens19
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-21 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN
2024-08-21 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN                                              NaN
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                        11.022960                                        13.334278                                        13.808910                                        13.893058                                        12.751099                                        10.380890                                         9.720493                                         8.375266                                        13.598948                                        12.753997                                         8.666895                                        12.630897                                         6.907444                                        12.856212                                        10.942675
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                        11.372863                                        13.562339                                        14.185448                                        13.893058                                        12.942011                                        10.346745                                        10.092934                                         8.354494                                        13.581390                                        12.837056                                         9.418065                                        12.715677                                         7.074159                                        12.713080                                        10.999074
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                        11.203362                                        13.187698                                        13.808910                                        13.893058                                        12.796611                                        10.380890                                         9.949841                                         8.259007                                        13.628883                                        12.751821                                         7.959279                                        12.334465                                         6.907444                                        12.856212                                        10.469760
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...                                              ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                         6.348952                                         8.177533                                         6.870938                                         8.947726                                         6.926277                                         6.814406                                         7.720705                                         5.604904                                         6.846745                                         7.785724                                         7.643766                                         5.713161                                         6.743453                                         6.273818                                         8.769368
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                         7.604732                                         8.449996                                         8.062087                                         9.899940                                        10.040489                                         7.329082                                         6.952653                                         5.227229                                         6.244451                                         9.449031                                         7.240996                                         7.084094                                         7.138500                                         6.547401                                         9.960898
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                        11.319582                                         6.546126                                         5.093612                                         6.967340                                         6.713998                                         4.189205                                         6.312367                                         4.724124                                         5.694854                                         5.514377                                         5.131160                                         6.806500                                         9.940780                                         6.304548                                         6.533747
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                        11.772445                                         6.634799                                         6.274928                                         7.872987                                         6.977126                                         6.339997                                         7.179182                                         5.403582                                         7.344654                                         6.026468                                         7.217127                                         6.149908                                        11.049918                                         6.867187                                         6.452347
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                                        11.286166                                         6.878518                                         5.739017                                         7.958879                                         6.867866                                         6.767631                                         7.501273                                         5.108875                                         7.919320                                         5.560740                                         7.444355                                         6.063440                                        10.837227                                         7.273791                                         6.288200

[13778 rows x 2201 columns]

## Meteo

In [5]:
newcols = [c for c in meteo.columns if c not in maindf]
print("NEW VARIABLES FROM METEO DATA:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, meteo[newcols]], axis=1)
maindf

NEW VARIABLES FROM METEO DATA:
+ g
+ pa
+ ppfd
+ prec
+ rh
+ swc_0.05
+ swc_0.15
+ swc_0.3
+ swc_0.05_soilvue
+ swc_0.1_soilvue
+ swc_0.2_soilvue
+ swc_0.3_soilvue
+ swc_0.4_soilvue
+ swc_0.5_soilvue
+ ta
+ ts_0.05
+ ts_0.15
+ ts_0.3
+ ts_0.05_soilvue
+ ts_0.1_soilvue
+ ts_0.2_soilvue
+ ts_0.3_soilvue
+ ts_0.4_soilvue
+ ts_0.5_soilvue
+ sw_in
+ sw_out
+ lw_in
+ lw_out
+ ta_is_meteoswiss
+ rh_is_meteoswiss
+ pa_is_meteoswiss
+ prec_is_meteoswiss
+ sw_in_is_meteoswiss
+ sw_out_is_meteoswiss
+ lw_in_is_meteoswiss
+ lw_out_is_meteoswiss
+ ppfd_is_meteoswiss
+ timesince_prec
+ vpd
+ ts_0.05_gfXG
+ FLAG_ts_0.05_gfXG_ISFILLED
+ ts_0.15_gfXG
+ FLAG_ts_0.15_gfXG_ISFILLED
+ ts_0.3_gfXG
+ FLAG_ts_0.3_gfXG_ISFILLED
+ swc_0.05_gfXG
+ FLAG_swc_0.05_gfXG_ISFILLED
+ swc_0.15_gfXG
+ FLAG_swc_0.15_gfXG_ISFILLED
+ swc_0.3_gfXG
+ FLAG_swc_0.3_gfXG_ISFILLED

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  ppfd_is_meteoswiss  timesince_prec       vpd  ts_0.05_gfXG  FLAG_ts_0.05_gfXG_ISFILLED  ts_0.15_gfXG  FLAG_ts_0.15_gfXG_ISFILLED  ts_0.3_gfXG  FLAG_ts_0.3_gfXG_ISFILLED  swc_0.05_gfXG  FLAG_swc_0.05_gfXG_ISFILLED  swc_0.15_gfXG  FLAG_swc_0.15_gfXG_ISFILLED  swc_0.3_gfXG  FLAG_swc_0.3_gfXG_ISFILLED
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-21 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                 NaN             NaN       NaN           NaN                         NaN           NaN                         NaN          NaN                        NaN            NaN                          NaN            NaN                          NaN           NaN                         NaN
2024-08-21 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                 NaN             NaN       NaN           NaN                         NaN           NaN                         NaN          NaN                        NaN            NaN                          NaN            NaN                          NaN           NaN                         NaN
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             1.0  0.141369     18.378518                         0.0     20.368518                         0.0    20.119259                        0.0      16.752412                          0.0      26.141747                          0.0     23.278843                         0.0
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             2.0  0.130055     18.130740                         0.0     20.217407                         0.0    20.092593                        0.0      16.707313                          0.0      26.144934                          0.0     23.268508                         0.0
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             3.0  0.118427     17.933333                         0.0     20.069630                         0.0    20.036296                        0.0      16.672328                          0.0      26.134158                          0.0     23.272999                         0.0
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                 ...             ...       ...           ...                         ...           ...                         ...          ...                        ...            ...                          ...            ...                          ...           ...                         ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             0.0  0.308913     18.192778                         0.0     18.566111                         0.0    17.300000                        0.0      27.981393                          0.0      29.086370                          0.0     24.709643                         0.0
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             0.0  0.275008     18.041666                         0.0     18.451111                         0.0    17.300000                        0.0      27.982679                          0.0      29.086370                          0.0     24.707201                         0.0
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             0.0  0.288298     17.903888                         0.0     18.398333                         0.0    17.269444                        0.0      27.975655                          0.0      29.082396                          0.0     24.680151                         0.0
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             0.0  0.276955     17.802222                         0.0     18.301111                         0.0    17.206667                        0.0      27.978823                          0.0      29.071958                          0.0     24.701179                         0.0
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                 0.0             0.0  0.239388     17.667816                         0.0     18.255747                         0.0    17.200000                        0.0      28.013870                          0.0      29.067775                          0.0     24.796206                         0.0

[13778 rows x 2252 columns]

## Management

In [6]:
newcols = [c for c in management.columns if c not in maindf]

# drop any that start with 'n_decay' or 'timesince' OR end with 'timed'
newcols = [
    c for c in newcols
    if not (c.startswith(('n_decay', 'timesince')) or c.endswith('timed'))
]

print("NEW VARIABLES FROM MANAGEMENT DATA:")
[print(f"+ {c}") for c in newcols]
maindf = pd.concat([maindf, management[newcols]], axis=1)
maindf

NEW VARIABLES FROM MANAGEMENT DATA:
+ fert
+ fert_min
+ fert_org
+ harvest
+ sowing
+ soil_preparation
+ nitrogen_fert
+ operation
+ crop_type
+ crop

                      AIR_CP  AIR_DENSITY    AIR_MV  AIR_RHO_CP  AOA_METHOD  AXES_ROTATION_METHOD  BADM_HEIGHTC  BADM_INSTPAIR_EASTWARD_SEP_GA_CH4  BADM_INSTPAIR_EASTWARD_SEP_GA_CO2  BADM_INSTPAIR_EASTWARD_SEP_GA_H2O  BADM_INSTPAIR_EASTWARD_SEP_GA_N2O  BADM_INSTPAIR_HEIGHT_SEP_GA_CH4  BADM_INSTPAIR_HEIGHT_SEP_GA_CO2  BADM_INSTPAIR_HEIGHT_SEP_GA_H2O  BADM_INSTPAIR_HEIGHT_SEP_GA_N2O  ...  FLAG_swc_0.05_gfXG_ISFILLED  swc_0.15_gfXG  FLAG_swc_0.15_gfXG_ISFILLED  swc_0.3_gfXG  FLAG_swc_0.3_gfXG_ISFILLED  fert  fert_min  fert_org  harvest  sowing  soil_preparation  nitrogen_fert  operation  crop_type  crop
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                 ...
2024-08-21 23:15:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                          NaN            NaN                          NaN           NaN                         NaN   NaN       NaN       NaN      NaN     NaN               NaN            NaN        NaN        NaN   NaN
2024-08-21 23:45:00      NaN          NaN       NaN         NaN         NaN                   NaN           NaN                                NaN                                NaN                                NaN                                NaN                              NaN                              NaN                              NaN                              NaN  ...                          NaN            NaN                          NaN           NaN                         NaN   NaN       NaN       NaN      NaN     NaN               NaN            NaN        NaN        NaN   NaN
2024-08-22 00:15:00  1012.16      1.16533  0.024738     1179.50         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      26.141747                          0.0     23.278843                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
2024-08-22 00:45:00  1012.11      1.16619  0.024721     1180.31         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      26.144934                          0.0     23.268508                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
2024-08-22 01:15:00  1012.10      1.16655  0.024713     1180.66         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      26.134158                          0.0     23.272999                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
...                      ...          ...       ...         ...         ...                   ...           ...                                ...                                ...                                ...                                ...                              ...                              ...                              ...                              ...  ...                          ...            ...                          ...           ...                         ...   ...       ...       ...      ...     ...               ...            ...        ...        ...   ...
2025-06-04 21:45:00  1013.91      1.14074  0.025243     1156.61         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      29.086370                          0.0     24.709643                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 22:15:00  1013.99      1.14144  0.025226     1157.41         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      29.086370                          0.0     24.707201                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 22:45:00  1014.01      1.14117  0.025232     1157.16         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      29.082396                          0.0     24.680151                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 23:15:00  1014.04      1.14156  0.025222     1157.59         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      29.071958                          0.0     24.701179                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 23:45:00  1013.47      1.14369  0.025185     1159.10         0.0                   1.0           0.5                               -4.5                                2.0                                2.0                               -4.5                             -3.0                             -2.5                             -2.5                             -3.0  ...                          0.0      29.067775                          0.0     24.796206                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0

[13778 rows x 2262 columns]

# CHECK DATASET PERIOD

In [7]:
# Restrict the product to the dataset period (safety cut).
# All inputs should already be restricted from the first notebooks on; if records outside
# the period are found here, an upstream output is outdated and should be re-run.
n_before = len(maindf)
outside = maindf.index[(maindf.index <= PERIOD_START) | (maindf.index >= PERIOD_END)]
if len(outside):
    print(f"WARNING: {len(outside)} records outside the dataset period were removed "
          f"({outside.min()} to {outside.max()}). Check that all upstream notebooks were re-run.")
maindf = select_period(maindf, timestamp='middle')

# Checks
assert maindf.index.is_unique, "Duplicated timestamps in the product"
expected = pd.date_range(PERIOD_START + pd.Timedelta('15min'), PERIOD_END - pd.Timedelta('15min'), freq='30min')
missing = expected.difference(maindf.index)
print(f"{len(maindf)} records from {maindf.index.min()} to {maindf.index.max()}; "
      f"missing 30-min timestamps: {len(missing)}")

WARNING: 2 records outside the dataset period were removed (2024-08-21 23:15:00 to 2024-08-21 23:45:00). Check that all upstream notebooks were re-run.

select_period: kept 13776 of 13778 records (2024-08-22 00:15:00 to 2025-06-04 23:45:00, timestamp=middle)
13776 records from 2024-08-22 00:15:00 to 2025-06-04 23:45:00; missing 30-min timestamps: 0

# CORE DATASET

The full product contains all variables of all processing steps (> 2000 columns). The core dataset contains the variables most users need:

- **Fluxes** NEE, FN2O, FCH4: u\*-filtered, quality-controlled measured fluxes and XGBoost gap-filled fluxes for the whole footprint and for parcels A and B, with gap-filling flags and uncertainties
- **NEE partitioning**: GPP and RECO (nighttime method) from the gap-filled NEE
- **LE, H**: measured (quality-controlled) and MDS gap-filled
- EddyPro random uncertainties, u\*, wind, u\* threshold, parcel attribution
- **Meteo and soil**: gap-filled meteorological variables (with MeteoSwiss flags) and gap-filled soil temperature and water content
- **Management**

Settings below define which u\* scenario and quality level are included. Columns that do not exist in the data are reported and skipped.

In [8]:
# --- Settings ---------------------------------------------------------------
USTAR_CUTS = ['16', '50', '84']        # u* scenarios to include, e.g. ['16', '50', '84']
QC_LEVELS = ['QCF0', 'QCF']       # 'QCF0' = highest quality only, 'QCF' = including flag 1
GASES = ['NEE', 'FN2O', 'FCH4']

# --- Column selection -----------------------------------------------------
core_cols = []

# Parcel attribution, turbulence and wind
core_cols += ['parcel', 'parcel_certainty', 'SW_IN_POT', 'USTAR', 'WS', 'WD',
              'Ustar_U50_Thres_reddyproc']

# Gas fluxes: measured, gap-filled, flags and uncertainty
for gas in GASES:
    for cut in USTAR_CUTS:
        for qc in QC_LEVELS:
            for area in ['footprint', 'parcelA', 'parcelB']:
                base = f'{gas}_L3.3_CUT_{cut}_{qc}_{area}'
                core_cols += [
                    base,                                     # measured, u*-filtered
                    f'{base}_gfXGBoost',                      # gap-filled
                    f'FLAG_{base}_gfXGBoost_ISFILLED',        # 1 = gap-filled value
                    f'{base}_gfXGBoost_sigmaGF',              # gap-filling uncertainty
                    f'{base}_gfXGBoost_total_unc',            # total uncertainty
                ]

# NEE partitioning (from gap-filled NEE; partitioning is done for the CUT_50 scenario only)
for qc in QC_LEVELS:
    for var in ['GPP_NT', 'RECO_NT']:
        core_cols.append(f'{var}_CUT_50_{qc}_footprint_gfXGBoost')

# Energy fluxes: measured (quality-controlled) and MDS gap-filled
core_cols += ['LE_L3.1_L3.2_QCF', 'LE_L3.2_QCF_footprint_gfMDS',
              'H_L3.1_L3.2_QCF', 'H_L3.2_QCF_footprint_gfMDS']

# Meteo (gap-filled with MeteoSwiss, see *_is_meteoswiss flags; Source: MeteoSwiss)
meteo_vars = ['ta', 'rh', 'vpd', 'pa', 'prec', 'sw_in', 'ppfd']
core_cols += meteo_vars
core_cols += [f'{v}_is_meteoswiss' for v in meteo_vars]

# Soil temperature and water content (gap-filled with XGBoost)
for var in ['ts', 'swc']:
    for depth in ['0.05', '0.15', '0.3']:
        core_cols += [f'{var}_{depth}_gfXG', f'FLAG_{var}_{depth}_gfXG_ISFILLED']

# Management
core_cols += [c for c in management.columns
              if not (c.startswith(('n_decay', 'timesince')) or c.endswith('timed'))]

# --- Build core dataframe ---------------------------------------------------
core_cols = list(dict.fromkeys(core_cols))               # remove duplicates, keep order
missing_cols = [c for c in core_cols if c not in maindf.columns]
core_cols = [c for c in core_cols if c in maindf.columns]

core = maindf[core_cols].copy()
# Add explicit start/end timestamps of each 30-min record (index is TIMESTAMP_MIDDLE, CET)
core.insert(0, 'TIMESTAMP_START', core.index - pd.Timedelta('15min'))
core.insert(1, 'TIMESTAMP_END', core.index + pd.Timedelta('15min'))

print(f"Core dataset: {core.shape[1]} columns, {core.shape[0]} records")
if missing_cols:
    print(f"\nNot found in data, skipped ({len(missing_cols)}):")
    [print(f"- {c}") for c in missing_cols]
core

Core dataset: 322 columns, 13776 records

Not found in data, skipped (1):
- vpd_is_meteoswiss

                        TIMESTAMP_START       TIMESTAMP_END parcel parcel_certainty  SW_IN_POT     USTAR        WS        WD  Ustar_U50_Thres_reddyproc  NEE_L3.3_CUT_16_QCF0_footprint  NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost  FLAG_NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_ISFILLED  NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_sigmaGF  NEE_L3.3_CUT_16_QCF0_footprint_gfXGBoost_total_unc  NEE_L3.3_CUT_16_QCF0_parcelA  ...  FLAG_swc_0.05_gfXG_ISFILLED  swc_0.15_gfXG  FLAG_swc_0.15_gfXG_ISFILLED  swc_0.3_gfXG  FLAG_swc_0.3_gfXG_ISFILLED  fert  fert_min  fert_org  harvest  sowing  soil_preparation  nitrogen_fert  operation  crop_type  crop
TIMESTAMP_MIDDLE                                                                                                                                                                                                                                                                                                                                                                                                               ...
2024-08-22 00:15:00 2024-08-22 00:00:00 2024-08-22 00:30:00      B          certain        0.0  0.013084  0.057826  206.8970                   0.065425                             NaN                                  3.345965                                                1.0                                               1.404445                                           1.404445                            NaN  ...                          0.0      26.141747                          0.0     23.278843                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
2024-08-22 00:45:00 2024-08-22 00:30:00 2024-08-22 01:00:00      A          certain        0.0  0.072340  0.136575  335.9810                   0.065425                             NaN                                  3.068731                                                1.0                                               0.868642                                           0.868642                            NaN  ...                          0.0      26.144934                          0.0     23.268508                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
2024-08-22 01:15:00 2024-08-22 01:00:00 2024-08-22 01:30:00      B        uncertain        0.0  0.075366  0.256552  249.7910                   0.065425                             NaN                                  3.345965                                                1.0                                               1.426479                                           1.426479                            NaN  ...                          0.0      26.134158                          0.0     23.272999                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
2024-08-22 01:45:00 2024-08-22 01:30:00 2024-08-22 02:00:00      A          certain        0.0  0.058658  0.571641  332.6240                   0.065425                        6.566236                                  6.566236                                                0.0                                               0.859312                                           1.585380                       6.566236  ...                          0.0      26.123198                          0.0     23.264485                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
2024-08-22 02:15:00 2024-08-22 02:00:00 2024-08-22 02:30:00      A          certain        0.0  0.035749  0.139619   21.0018                   0.065425                             NaN                                  2.730714                                                1.0                                               0.847036                                           0.847036                            NaN  ...                          0.0      26.132820                          0.0     23.234120                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None       None   2.0
...                                 ...                 ...    ...              ...        ...       ...       ...       ...                        ...                             ...                                       ...                                                ...                                                    ...                                                ...                            ...  ...                          ...            ...                          ...           ...                         ...   ...       ...       ...      ...     ...               ...            ...        ...        ...   ...
2025-06-04 21:45:00 2025-06-04 21:30:00 2025-06-04 22:00:00      B          certain        0.0  0.413091  3.946670  223.4950                   0.098312                       10.578562                                 10.578562                                                0.0                                               1.801869                                           0.510651                            NaN  ...                          0.0      29.086370                          0.0     24.709643                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 22:15:00 2025-06-04 22:00:00 2025-06-04 22:30:00      B          certain        0.0  0.353844  3.396350  224.0890                   0.098312                        9.416519                                  9.416519                                                0.0                                               1.781323                                           0.432552                            NaN  ...                          0.0      29.086370                          0.0     24.707201                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 22:45:00 2025-06-04 22:30:00 2025-06-04 23:00:00      B          certain        0.0  0.409273  3.554130  218.4310                   0.098312                       10.095010                                 10.095010                                                0.0                                               1.783623                                           0.580992                            NaN  ...                          0.0      29.082396                          0.0     24.680151                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 23:15:00 2025-06-04 23:00:00 2025-06-04 23:30:00      B          certain        0.0  0.330784  3.337320  208.1570                        NaN                             NaN                                  9.624490                                                1.0                                               1.769763                                           1.769763                            NaN  ...                          0.0      29.071958                          0.0     24.701179                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0
2025-06-04 23:45:00 2025-06-04 23:30:00 2025-06-05 00:00:00      B          certain        0.0  0.375659  3.674110  221.9010                        NaN                             NaN                                  9.135176                                                1.0                                               1.789836                                           1.789836                            NaN  ...                          0.0      29.067775                          0.0     24.796206                         0.0   0.0       0.0       0.0      0.0     0.0               0.0            0.0       None  grassland   3.0

[13776 rows x 322 columns]

# EXPORT

In [9]:
NAME = "CH-TAN_ley_2024-25_FLUXES_METEO_MGMT"

# Full product: all variables (parquet only, too large for csv)
filename_full = f"90.1_{NAME}_FULL"
save_parquet(data=maindf, filename=filename_full)

# Core product: parquet and csv
filename_core = f"90.2_{NAME}_CORE"
save_parquet(data=core, filename=filename_core)
core.to_csv(f"{filename_core}.csv", index=True)
print(f"Saved {filename_core}.csv")

Saved file 90.1_CH-TAN_ley_2024-25_FLUXES_METEO_MGMT_FULL.parquet (2.728 seconds).

Saved file 90.2_CH-TAN_ley_2024-25_FLUXES_METEO_MGMT_CORE.parquet (0.431 seconds).

Saved 90.2_CH-TAN_ley_2024-25_FLUXES_METEO_MGMT_CORE.csv

# **End of notebook**

In [10]:
from datetime import datetime
dt_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Finished. {dt_string}")

Finished. 2026-10-07 14:51:50